define({
		'sim_common_start' : 'Reproducir',
		'sim_common_stop' : 'Detener',
		'sim_common_error_button' : 'Generar error',
		'sim_common_error_pending_button' : 'Pendiente de error',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'Siguiente',
		'sim_accelerometer_startStop_button' : 'Iniciar / Detener',

		'sim_battery_plugedIn_label' : 'Conectado:',
		'sim_battery_batteryLevel_label' : 'Nivel de batería:',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : 'Elija una imagen que se utilizará para la cámara:',
		'sim_camera_currently_selected_camera' : 'Imagen seleccionada actualmente par la cámara:',
		'sim_camera_choose_image_album_library' : 'Elija una imagen que se utilizará para el álbum/la biblioteca.',
		'sim_camera_currently_selected_album_library' : 'Imagen seleccionada actualmente para el álbum/la biblioteca:',
		'sim_camera_cannotLoadApplet' : "La simulación de API de cámara está inhabilitada (el applet no se ha cargado, compruebe los valores de Java)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Elija archivo de audio',
		'sim_capture_audio1' : 'Audio 1',
		'sim_capture_audio2' : 'Audio 2',
		'sim_capture_audio3' : 'Audio 3',
		'sim_capture_playAudio' : 'Reproducir',
		'sim_capture_choose_video' : 'Elija archivo de vídeo',
		'sim_capture_video1' : 'Vídeo 1',
		'sim_capture_video2' : 'Vídeo 2',
		'sim_capture_video3' : 'Vídeo 3',
		'sim_capture_playVideo' : 'Reproducir',
		'sim_capture_browserSupport' : 'La interfaz de usuario de simulación de captura está disponible con Google Chrome y Mozilla Firefox.',
		'sim_capture_cannotLoadApplet' : "La simulación de API de la captura está inhabilitada (el applet no se ha cargado, compruebe los valores de Java)",
		'sim_compass_error_random' : 'Generar error aleatorio',
		'sim_compass_generate' : 'Generar',

		'sim_compass_heading_label' : 'Cabecera:',
		'sim_compass_next_button' : 'Siguiente',
		'sim_compass_startStop_button' : 'Iniciar / Detener',
		'sim_compass_error_button' : 'Generar error',

		'sim_contacts_refresh_label' : 'Renovar',
		'sim_contacts_nowebsql' : 'La simulación de API de contactos de Cordova está inhabilitada porque WebSQL no está soportada en este navegador.',

		'sim_device_select_label' : 'Seleccionar dispositivo:',
		'sim_device_prev_button' : 'Anterior',
		'sim_device_next_button' : 'Siguiente',
		'sim_device_no_version_info' : 'No hay información de versión',

		'sim_events_pause_button' : 'Pausa',
		'sim_events_resume_button' : 'Reanudar',
		'sim_events_back_button' : 'Atrás',
		'sim_events_menu_button' : 'Menú',
		'sim_events_search_button' : 'Búsqueda',
		'sim_events_online_button' : 'En línea',
		'sim_events_offline_button' : 'Fuera de línea',
		'sim_events_startCall_button' : 'Iniciar llamada',
		'sim_events_endCall_button' : 'Finalizar llamada',
		'sim_events_volumeUp_button' : 'Subir volumen',
		'sim_events_volumeDown_button' : 'Bajar volumen',

		'sim_file_refresh_button' : "Renovar",
		'sim_file_cannotLoadApplet' : "La simulación de API del archivo está inhabilitada (el applet no se ha cargado, compruebe los valores de Java)",
		'sim_geoloc_longitude_label' : 'Longitud',
		'sim_geoloc_latitude_label' : 'Latitud',
		'sim_geoloc_accuracy_label' : 'Precisión',
		'sim_geoloc_altitude_label' : 'Altitud',
		'sim_geoloc_altitudeAccuracy_label' : 'Precisión de altitud',
		'sim_geoloc_heading_label' : 'Cabecera',
		'sim_geoloc_velocity_label' : 'Velocidad(m/s)',
		'sim_geoloc_next_button' : "Paso",
		'sim_geoloc_startStop_button' : "Reproducir / Detener",
		'sim_geoloc_usingFFgeolocation' : "Utilización del servicio de geolocalización que se proporciona con Firefox.",
		'sim_geoloc_apply_tooltip' : "Pulse aplicar para que los cambios surtan efecto",
		'sim_geoloc_step_tooltip' : "Muévase una vez según la cabecera y la velocidad por 1 segundo.",
		'sim_geoloc_startStop_tooltip' : "Empiece a moverse según la cabecera y la velocidad.",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : 'Reproducir',
		'sim_media_length_label' : 'Longitud',
		'sim_media_audioRecording_label' : 'Grabación de audio',
		'sim_media_audioRecording_status' : 'Desocupado',
		'sim_media_audioRecording_idle' : 'Desocupado',
		'sim_media_audioRecording_recording' : 'Grabación',

		'sim_network_none' : 'Ninguno',
		'sim_network_ethernet' : 'Red Ethernet',
		'sim_network_wifi' : 'Red de wifi',
		'sim_network_2g' : 'Red 2G',
		'sim_network_3g' : 'Red 3G',
		'sim_network_4g' : 'Red 4G',
		'sim_network_cell' : 'Conexión genérica de celda',
		'sim_network_unknown' : 'Red desconocida',
		'sim_scenario_warning' : 'Aviso',
		'sim_scenario_unsaved_text' : '<h3>Tiene cambios no guardados en el caso de ejemplo actual.</h3><h3>Si opta por continuar, se perderán esos cambios.</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Latitud, longitud (grados decimales, por ejemplo -118,15, 34,03)',
		'sim_scenario_usingFFgeolocation' : "El widget de caso de ejemplo no está soportado en Firefox.",
		'sim_scenario_usingIEgeolocation' : "El widget de caso de ejemplo no está soportado en Internet Explorer.",
		'sim_scenario_new' : 'Nuevo',
		'sim_scenario_delete' : 'Suprimir',
		'sim_scenario_delete_path' : 'Suprimir vía de acceso',
		'sim_scenario_save' : 'Guarde',
		'sim_scenario_pause' : 'Pausa',
		'sim_scenario_play' : 'Reproducir',
		'sim_scenario_restart' : 'Reiniciar',
		'sim_scenario_continue' : 'Continuar',
		'sim_scenario_edit' : 'Editar',
		'sim_scenario_go' : 'Ir',
		'sim_scenario_cancel' : 'Cancelar',
		'sim_scenario_export' : 'Exportar',
		'sim_scenario_apply' : 'Aplicar',
		'sim_scenario_editor_name' : 'Nombre:',
		'sim_scenario_editor_name_textbox_placeholder' : 'Nombre de caso de ejemplo',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Nombre de caso de ejemplo</p>',
		'sim_scenario_editor_speed_label' : 'Velocidad(m/s)',
		'sim_scenario_editor_time_label' : 'Tiempo (s)',
		'sim_scenario_editor_no_gps_zone_title' : 'Zona sin GPS',
		'sim_scenario_editor_access_point_title' : 'Punto de acceso',
		'sim_scenario_editor_route_point_title' : 'Punto de ruta',
		'sim_scenario_editor_path_tooltip' : '<p>Crear una vía de acceso simulada de un dispositvo móvil:</p>'+
												'<ul><li>Pulse el mapa para añadir vértices (puntos) a la vía de acceso</li><li>Efectúe una doble pulsación cuando finalice</li></ul>' +
												'<p>Una vez creada la vía de acceso, pulse un vértice para moverla o editar sus propiedades.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>Crear una zona WiFi:</p>'+
												'<ul><li>Arrastre el ratón para crear el área de cobertura de WiFi.</li></ul>' +
												'<p>Una vez creada la zona de WiFi, pulse la zona para moverla o editar sus propiedades.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>Cree una zona sin cobertura de GPS:</p>'+
												'<ul><li>Pulse el mapa para añadir vértices (puntos) a la zona</li><li>Efectúe una doble pulsación cuando finalice</li></ul>' +
												'<p>Una vez creada la zona Sin GPS, pulse la zona para moverla o editar sus propiedades.</p>'
});

