//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'Когда веб-страницы просматриваются не на сервере клиента тестирования, клиент тестирования начинает работать значительно медленнее.',

	'index_title' : 'Эмулятор браузера мобильных устройств',
	'index_desc' : 'Эмулятор браузера мобильных устройств позволяет просматривать веб-страницы в форматах, поддерживаемых различными браузерами мобильных устройств.',
	'index_webpage' : 'Веб-страница:',
	'index_go' : 'Перейти/обновить',
	'index_go_simple_preview' : 'Упрощенный предварительный просмотр',
	'index_scale' : 'Масштаб для всех устройств:',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'По размеру окна',
	'index_scale_physical' : 'По размеру физического устройства',
	'index_add_device' : 'Добавить устройство',
	'index_calibrate' : 'Отрегулировать физический размер',
	'index_calibrate_dialog_title' : 'Регулировка физического размера',
	'index_scaling_warning' : 'Эмулятор браузера мобильных устройств не поддерживает масштабирование содержимого в этом браузере. Масштабирование содержимого поддерживается только в последней версии Firefox и в Internet Explorer версии 9 или более поздней.',
	'index_xdomain_warning' : 'Показанная веб-страница и данный клиент тестирования находятся на разных серверах.',
	'index_enable_useragent_switching' : 'Включить смену пользовательского агента',
	'index_useragent_switching_desc' : 'Функция смены ИД пользовательского агента позволяет изменять ИД пользовательского агента, для того чтобы при загрузке страницы в эмулятор она запрашивалась с применением правильного ИД пользовательского агента.',
	'index_useragent_switching_support' : 'Смена пользовательского агента поддерживается в следующих браузерах:',
	'index_useragent_extension_install_title' : 'Установить расширение для смены пользовательского агента',
	'index_useragent_extension_install_instructions_1' : 'Для того чтобы Эмулятор браузера мобильных устройств автоматически менял строку ИД пользовательского агента, в браузере должно быть установлено специальное расширение.',
	'index_useragent_extension_install_instructions_2' : 'Эмулятор обнаружил, что последняя версия расширения не установлена. Установите последнюю версию расширения в текущий браузер, перейдя по указанной выше ссылке.',
	'index_useragent_extension_install_btn' : 'Установить расширение браузера',
	'index_useragent_extension_install_instructions_chrome1' : 'Примечание: Если при попытке установить расширение получено сообщение \"Расширения, приложения и пользовательские сценарии можно добавить только из Chrome Web Store.\", то расширение необходимо установить вручную. Для этого нужно выполнить следующие действия:',
	'index_useragent_extension_install_instructions_chrome2' : 'Откройте параметры Chrome',
	'index_useragent_extension_install_instructions_chrome3' : 'Перейдите на страницу расширений Chrome',
	'index_useragent_extension_install_instructions_chrome4' : 'Перенесите загруженный файл расширения из панели инструментов загрузки на страницу расширений.',
	'index_need_http' : "В случае указания полного пути он должен начинаться с 'http://'.",
	'index_splash_title' : "Загрузка...",
	'index_splash_status' : "Эмулятор будет скоро готов к работе.",	
	'MobileDeviceTree_by_platform' : 'По платформе',
	'MobileDeviceTree_by_resolution' : 'По разрешению',
	'MobileDeviceTree_platforms' : 'Платформы',
	'MobileDeviceTree_resolutions' : 'Разрешения',
	'MobileBrowserSimulator_rotate' : 'Повернуть',
	'MobileBrowserSimulator_remove_device': 'Удалить устройство',
	'MobileBrowserSimulator_xdomain_warning' : 'Показанная веб-страница и данный клиент тестирования находятся на разных серверах.',
	'MobileBrowserSimulator_skin' : 'Оболочка',
	'QRCodeTooltip' : 'Отсканируйте этот QR-код для загрузки имитации веб-страницы на свое мобильное устройство.',
	'QRCodeIPTooltip' : 'Необходимо выбрать или ввести IP-адрес или имя хоста, которые будут применяться для доступа к имитации веб-страницы на вашем мобильном устройстве.',
	'QRCodeIPHostName' : 'IP-адрес или имя хоста',
	'PPICalculator_desc' : 'Для просмотра страницы в эмуляторе, масштабированной по физическому размеру различных мобильных устройств, размер эмулятора должен быть адаптирован под текущий монитор:',
	'PPICalculator_step_1' : 'Приложите кредитную карту стандартного размера к экрану так, чтобы ее верхний край совпал со сплошной черной линией.',
	'PPICalculator_step_2' : 'Переместите прерывистую серую линию с помощью мыши или клавиш со стрелками так, чтобы она совпала с нижним краем карты.',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "Текущая версия применяемого веб-браузера поддерживается лишь частично.",
	'Downgrade' : "Необходимо понизить версию до уровня",
	'Upgrade' : "Необходимо обновить версию до уровня",
	'OrLater' : "или выше",
	'Firefox_version_warning' : "Смена пользовательского агента в зависимости от устройства не поддерживается в Firefox версий 17-22.",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "Имитировать API устройства",
	'index_cordova_enable_desc' : 'Включить имитацию API Apache Cordova.',	
	'index_cordova_support' : 'Имитация Apache Cordova поддерживается в среде Android, iPhone, iPad, Windows Phone, Windows 8 и BlackBerry 10 и доступна только в следующих браузерах:'

//end v1.x content
});

