define({
		'sim_common_start' : 'Riproduci',
		'sim_common_stop' : 'Arresto',
		'sim_common_error_button' : 'Genera errore',
		'sim_common_error_pending_button' : 'Errore in sospeso',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'Avanti',
		'sim_accelerometer_startStop_button' : 'Avvia / Arresta',

		'sim_battery_plugedIn_label' : 'Collegato:',
		'sim_battery_batteryLevel_label' : 'Livello batteria:',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : 'Scegliere un\'immagine da utilizzare per la macchina fotografica:',
		'sim_camera_currently_selected_camera' : 'Immagine attualmente selezionata per la macchina fotografica:',
		'sim_camera_choose_image_album_library' : 'Scegliere un\'immagine da utilizzare per l\'album/libreria:',
		'sim_camera_currently_selected_album_library' : 'Immagine attualmente selezionata per l\'album/libreria:',
		'sim_camera_cannotLoadApplet' : "La simulazione API per macchina fotografica è disabilitata (l'applet non è caricata, verificare le impostazioni Java)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Scegli file audio',
		'sim_capture_audio1' : 'Audio 1',
		'sim_capture_audio2' : 'Audio 2',
		'sim_capture_audio3' : 'Audio 3',
		'sim_capture_playAudio' : 'Riproduci',
		'sim_capture_choose_video' : 'Scegli file video',
		'sim_capture_video1' : 'Video 1',
		'sim_capture_video2' : 'Video 2',
		'sim_capture_video3' : 'Video 3',
		'sim_capture_playVideo' : 'Riproduci',
		'sim_capture_browserSupport' : 'L\'UI di simulazione dell\'acquisizione è disponibile con Google Chrome e Mozilla Firefox.',
		'sim_capture_cannotLoadApplet' : "La simulazione API cattura è disabilitata (applet non caricato, verificare le impostazioni Java)",
		'sim_compass_error_random' : 'Genera errore casuale',
		'sim_compass_generate' : 'Genera',

		'sim_compass_heading_label' : 'Intestazione:',
		'sim_compass_next_button' : 'Avanti',
		'sim_compass_startStop_button' : 'Avvia / Arresta',
		'sim_compass_error_button' : 'Genera errore',

		'sim_contacts_refresh_label' : 'Aggiorna',
		'sim_contacts_nowebsql' : 'La simulazione API dei contatti Cordova è disabilitata perché WebSQL non è supportato in questo browser.',

		'sim_device_select_label' : 'Seleziona dispositivo:',
		'sim_device_prev_button' : 'Indietro',
		'sim_device_next_button' : 'Avanti',
		'sim_device_no_version_info' : 'Nessuna informazione sulla versione',

		'sim_events_pause_button' : 'Sospendi',
		'sim_events_resume_button' : 'Riprendi',
		'sim_events_back_button' : 'Indietro',
		'sim_events_menu_button' : 'Menu',
		'sim_events_search_button' : 'Cerca',
		'sim_events_online_button' : 'Online',
		'sim_events_offline_button' : 'Offline',
		'sim_events_startCall_button' : 'Inizio chiamata',
		'sim_events_endCall_button' : 'Fine chiamata',
		'sim_events_volumeUp_button' : 'Aumenta volume',
		'sim_events_volumeDown_button' : 'Diminuisci volume',

		'sim_file_refresh_button' : "Aggiorna",
		'sim_file_cannotLoadApplet' : "La simulazione API file è disabilitata (applet non caricato, verificare le impostazioni Java)",
		'sim_geoloc_longitude_label' : 'Longitudine',
		'sim_geoloc_latitude_label' : 'Latitudine',
		'sim_geoloc_accuracy_label' : 'Precisione',
		'sim_geoloc_altitude_label' : 'Altitudine',
		'sim_geoloc_altitudeAccuracy_label' : 'Precisione altitudine',
		'sim_geoloc_heading_label' : 'Intestazione',
		'sim_geoloc_velocity_label' : 'Velocità(m/s)',
		'sim_geoloc_next_button' : "Fase",
		'sim_geoloc_startStop_button' : "Riproduci / Arresta",
		'sim_geoloc_usingFFgeolocation' : "Utilizza il sevizio di georilevazione fornito da Firefox.",
		'sim_geoloc_apply_tooltip' : "Premere Applica affinché le modifiche abbiano effetto",
		'sim_geoloc_step_tooltip' : "Spostare una volta in base all'intestazione e alla velocità per 1 secondo.",
		'sim_geoloc_startStop_tooltip' : "Comincia lo spostamento in base all'intestazione e alla velocità.",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : 'Riproduzione',
		'sim_media_length_label' : 'Lunghezza',
		'sim_media_audioRecording_label' : 'Registrazione audio',
		'sim_media_audioRecording_status' : 'Inattivo',
		'sim_media_audioRecording_idle' : 'Inattivo',
		'sim_media_audioRecording_recording' : 'Registrazione',

		'sim_network_none' : 'Nessuno',
		'sim_network_ethernet' : 'Rete Ethernet',
		'sim_network_wifi' : 'Rete Wifi',
		'sim_network_2g' : 'Rete 2G',
		'sim_network_3g' : 'Rete 3G',
		'sim_network_4g' : 'Rete 4G',
		'sim_network_cell' : 'Connessione generica cella',
		'sim_network_unknown' : 'Rete sconosciuta',
		'sim_scenario_warning' : 'Avvertenza',
		'sim_scenario_unsaved_text' : '<h3>Lo scenario corrente contiene modifiche non salvate. </h3><h3>Se si sceglie di continuare, le modifiche andranno perse.</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Latitudine, Longitudine (gradi decimali, ad esempio -118.15, 34.03)',
		'sim_scenario_usingFFgeolocation' : "Il widget scenario non è supportato in Firefox.",
		'sim_scenario_usingIEgeolocation' : "Il widget scenario non è supportato in Internet Explorer.",
		'sim_scenario_new' : 'Nuovo',
		'sim_scenario_delete' : 'Elimina',
		'sim_scenario_delete_path' : 'Elimina percorso',
		'sim_scenario_save' : 'Salva',
		'sim_scenario_pause' : 'Sospendi',
		'sim_scenario_play' : 'Riproduci',
		'sim_scenario_restart' : 'Riavvia',
		'sim_scenario_continue' : 'Continua',
		'sim_scenario_edit' : 'Modifica',
		'sim_scenario_go' : 'Vai',
		'sim_scenario_cancel' : 'Annulla',
		'sim_scenario_export' : 'Esportazione',
		'sim_scenario_apply' : 'Applica',
		'sim_scenario_editor_name' : 'Nome:',
		'sim_scenario_editor_name_textbox_placeholder' : 'Nome scenario',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Nome scenario</p>',
		'sim_scenario_editor_speed_label' : 'Velocità (m/s)',
		'sim_scenario_editor_time_label' : 'Ora',
		'sim_scenario_editor_no_gps_zone_title' : 'Nessuna zona GPS',
		'sim_scenario_editor_access_point_title' : 'Punto di accesso',
		'sim_scenario_editor_route_point_title' : 'Punto di indirizzamento',
		'sim_scenario_editor_path_tooltip' : '<p>Crea un percorso simulato di un dispositivo mobile:</p>'+
												'<ul><li>Fare clic sulla mappa per aggiungere vertici (punti) al percorso</li><li>Al termine, fare doppio clic</li></ul>' +
												'<p>Dopo aver creato il percorso, fare clic su un vertice per spostarlo o per modificarne le proprietà.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>Creare una zona WiFi:</p>'+
												'<ul><li>Trascinare il mouse per creare l\'area di copertura WiFi.</li></ul>' +
												'<p>Dopo aver creato la zona WiFi, fare clic sulla zona per spostarla o modificarne le proprietà.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>Creare una zona senza copertura GPS:</p>'+
												'<ul><li>Fare clic sulla mappa per aggiungere vertici (punti) alla zona</li><li>Al termine, fare doppio clic</li></ul>' +
												'<p>Dopo aver creato la zona Senza GPS, fare clic sulla zona per spostarla o modificarne le proprietà.</p>'
});

