//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'La visualizzazione delle pagine Web non effettuata sul server del client di test, comporterà una riduzione significativa nella funzionalità del client di test.',

	'index_title' : 'Mobile Browser Simulator',
	'index_desc' : 'Mobile Browser Simulator mostra le pagine Web in diverse dimensioni e forme di browser mobili.',
	'index_webpage' : 'Pagina Web:',
	'index_go' : 'Vai / Aggiorna',
	'index_go_simple_preview' : 'Apri anteprima semplice',
	'index_scale' : 'Scala tutti i dispositivi',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'Adatta alla finestra',
	'index_scale_physical' : 'Dimensione dispositivo fisico',
	'index_add_device' : 'Aggiungi dispositivo',
	'index_calibrate' : 'Calibra dimensione fisica',
	'index_calibrate_dialog_title' : 'Calibratura dimensione fisica',
	'index_scaling_warning' : 'Mobile Browser Simulator non supporta il ridimensionamento del contenuto in questo browser. Mobile Browser Simulator supporta il ridimensionamento del contenuto nella ultima versione di Mozilla Firefox o in Internet Explorer 9 e versioni successive.',
	'index_xdomain_warning' : 'La pagina Web attualmente visualizzata si trova in un server diverso da questo client di test. ',
	'index_enable_useragent_switching' : 'Abilita switch agent utente',
	'index_useragent_switching_desc' : 'Lo switch di ID agent utente consente al simulatore di cambiare ID agent utente nel browser, quindi, quando una pagina viene caricata nel simulatore, questa viene richiesta mediante la stringa ID agent utente corretta.',
	'index_useragent_switching_support' : 'Lo switch di agent utente è supportato sui seguenti browser:',
	'index_useragent_extension_install_title' : 'Installa estensione Useragent Switcher',
	'index_useragent_extension_install_instructions_1' : 'Affinché Mobile Browser Simulator possa cambiare automaticamente la stringa ID agent utente, è necessario installare una estensione nel browser.',
	'index_useragent_extension_install_instructions_2' : 'Il simulatore ha rilevato che non è installata una versione corrente dell\'estensione. Utilizzare il link seguente per installare l\'ultima estensione per il browser corrente.',
	'index_useragent_extension_install_btn' : 'Installa estensione browser',
	'index_useragent_extension_install_instructions_chrome1' : 'Nota: se dopo aver installato una estensione viene visualizzato il seguente messaggio \"Le estensioni, le applicazioni e gli script utente possono essere aggiunti solo da Chrome Web Store.\", sarà necessario installare manualmente 1 estensione. Attenersi alla seguente procedura:',
	'index_useragent_extension_install_instructions_chrome2' : 'Aprire le impostazioni di Chrome',
	'index_useragent_extension_install_instructions_chrome3' : 'Passare alla pagina delle estensioni di Chrome',
	'index_useragent_extension_install_instructions_chrome4' : 'Trascinare il file di estensioni scaricato dalla barra degli strumenti di download alla pagina delle estensioni.',
	'index_need_http' : "Quando non si utilizza alcun percorso relativo, 'http://' deve precedere il percorso.",
	'index_splash_title' : "Caricamento in corso...",
	'index_splash_status' : "Il simulatore sarà pronto tra qualche istante.",	
	'MobileDeviceTree_by_platform' : 'Per piattaforma',
	'MobileDeviceTree_by_resolution' : 'Per risoluzione',
	'MobileDeviceTree_platforms' : 'Piattaforme',
	'MobileDeviceTree_resolutions' : 'Risoluzioni',
	'MobileBrowserSimulator_rotate' : 'Ruota',
	'MobileBrowserSimulator_remove_device': 'Rimuovi dispositivo',
	'MobileBrowserSimulator_xdomain_warning' : 'La pagina Web attualmente visualizzata si trova su un server diverso dal client di test.',
	'MobileBrowserSimulator_skin' : 'Skin',
	'QRCodeTooltip' : 'Scannerizzare questo QRCode per caricare la pagina Web simulata sul dispositivo mobile.',
	'QRCodeIPTooltip' : 'È necessario scegliere/immettere l\'IP o il nome host che verrà utilizzato per accedere alla pagina Web simulata dal dispositivo mobile. ',
	'QRCodeIPHostName' : 'IP/Nome host',
	'PPICalculator_desc' : 'Per visualizzare la pagina in esecuzione nel simulatore nella dimensione fisica che assume nei diversi dispositivi mobili, è necessario calibrare il simulatore in base al monitor corrente:',
	'PPICalculator_step_1' : 'Posizionare una carta di credito di dimensioni standard sullo schermo in modo che la carta sia allineata con la riga nera continua.',
	'PPICalculator_step_2' : 'Trascinare la linea grigia tratteggiata o utilizzare i tasti freccia per allineare con la parte inferiore della carta.',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "La versione corrente del browser Web non è completamente supportata.",
	'Downgrade' : "È necessario passare alla precedente versione",
	'Upgrade' : "È necessario passare alla successiva versione",
	'OrLater' : "o successiva",
	'Firefox_version_warning' : "Il passaggio a un altro agent utente per dispositivo non è supportato su Firefox versioni 17-22.",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "Simula API dispositivo",
	'index_cordova_enable_desc' : 'Abilita la simulazione Apache Cordova API.',	
	'index_cordova_support' : 'La simulazione Apache Cordova è supportata in ambiente Android, iPhone, iPad, Windows Phone, Windows 8 e BlackBerry 10 ed è disponibile solo nei seguenti browser:'

//end v1.x content
});

