define({
		'sim_common_start' : 'Lejátszás',
		'sim_common_stop' : 'Leállítás',
		'sim_common_error_button' : 'Hiba előállítása',
		'sim_common_error_pending_button' : 'Hiba függőben',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'Következő',
		'sim_accelerometer_startStop_button' : 'Indítás / Leállítás',

		'sim_battery_plugedIn_label' : 'Bedugva:',
		'sim_battery_batteryLevel_label' : 'Akkumulátor szint:',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : 'Kamerához használt kép kiválasztása:',
		'sim_camera_currently_selected_camera' : 'Kamerához jelenleg kijelölt kép:',
		'sim_camera_choose_image_album_library' : 'Albumhoz/könyvtárhoz használt kép kiválasztása:',
		'sim_camera_currently_selected_album_library' : 'Albumhoz/könyvtárhoz jelenleg kijelölt kép:',
		'sim_camera_cannotLoadApplet' : "A kamera API szimuláció tiltott (a kisalkalmazás nem került betöltésre, ellenőrizze a Java beállításokat)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Audio fájl(ok) kiválasztása',
		'sim_capture_audio1' : 'Audio 1',
		'sim_capture_audio2' : 'Audio 2',
		'sim_capture_audio3' : 'Audio 3',
		'sim_capture_playAudio' : 'Lejátszás',
		'sim_capture_choose_video' : 'Videó fájl(ok) kiválasztása',
		'sim_capture_video1' : 'Video 1',
		'sim_capture_video2' : 'Video 2',
		'sim_capture_video3' : 'Video 3',
		'sim_capture_playVideo' : 'Lejátszás',
		'sim_capture_browserSupport' : 'A lementési szimulációs felület Google Chrome és Mozilla Firefox böngészőkkel áll rendelkezésre.',
		'sim_capture_cannotLoadApplet' : "A lementési API szimuláció tiltott (a kisalkalmazás nem került betöltésre, ellenőrizze a Java beállításokat)",
		'sim_compass_error_random' : 'Véletlen hiba előállítása',
		'sim_compass_generate' : 'Előállítás',

		'sim_compass_heading_label' : 'Fejléc:',
		'sim_compass_next_button' : 'Következő',
		'sim_compass_startStop_button' : 'Indítás / Leállítás',
		'sim_compass_error_button' : 'Hiba előállítása',

		'sim_contacts_refresh_label' : 'Frissítés',
		'sim_contacts_nowebsql' : 'A Cordova kapcsolattartók API tiltott, mert a WebSQL ebben a böngészőben nem támogatott.',

		'sim_device_select_label' : 'Eszköz kiválasztása:',
		'sim_device_prev_button' : 'Előző',
		'sim_device_next_button' : 'Következő',
		'sim_device_no_version_info' : 'Nincsenek változat információk',

		'sim_events_pause_button' : 'Szünet',
		'sim_events_resume_button' : 'Folytatás',
		'sim_events_back_button' : 'Vissza',
		'sim_events_menu_button' : 'Menü',
		'sim_events_search_button' : 'Keresés',
		'sim_events_online_button' : 'Online',
		'sim_events_offline_button' : 'Offline',
		'sim_events_startCall_button' : 'Hívás kezdeményezése',
		'sim_events_endCall_button' : 'Hívás befejezése',
		'sim_events_volumeUp_button' : 'Hangerő fel',
		'sim_events_volumeDown_button' : 'Hangerő le',

		'sim_file_refresh_button' : "Frissítés",
		'sim_file_cannotLoadApplet' : "A fájl API szimuláció tiltott (a kisalkalmazás nem került betöltésre, ellenőrizze a Java beállításokat)",
		'sim_geoloc_longitude_label' : 'Földrajzi hosszúság',
		'sim_geoloc_latitude_label' : 'Földrajzi szélesség',
		'sim_geoloc_accuracy_label' : 'Pontosság',
		'sim_geoloc_altitude_label' : 'Magasság',
		'sim_geoloc_altitudeAccuracy_label' : 'Magasság pontossága',
		'sim_geoloc_heading_label' : 'Fejléc',
		'sim_geoloc_velocity_label' : 'Sebesség (m/s)',
		'sim_geoloc_next_button' : "Lépés",
		'sim_geoloc_startStop_button' : "Lejátszás / Leállítás",
		'sim_geoloc_usingFFgeolocation' : "A Firefox böngészőhöz biztosított geolocation szolgáltatás használatával.",
		'sim_geoloc_apply_tooltip' : "A változások érvényre juttatásához kattintson az Alkalmaz gombra. ",
		'sim_geoloc_step_tooltip' : "Egy mozgás az iránynak és sebességnek megfelelően másodpercenként. ",
		'sim_geoloc_startStop_tooltip' : "Mozgás indítása az iránynak és sebességnek megfelelően. ",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : 'Visszajátszás',
		'sim_media_length_label' : 'Hossz',
		'sim_media_audioRecording_label' : 'Audio felvétel',
		'sim_media_audioRecording_status' : 'Tétlen',
		'sim_media_audioRecording_idle' : 'Tétlen',
		'sim_media_audioRecording_recording' : 'Felvétel',

		'sim_network_none' : 'Nincs',
		'sim_network_ethernet' : 'Ethernet hálózat',
		'sim_network_wifi' : 'Wifi hálózat',
		'sim_network_2g' : '2G hálózat',
		'sim_network_3g' : '3G hálózat',
		'sim_network_4g' : '4G hálózat',
		'sim_network_cell' : 'Általános mobil kapcsolat',
		'sim_network_unknown' : 'Ismeretlen hálózat',
		'sim_scenario_warning' : 'Figyelmeztetés',
		'sim_scenario_unsaved_text' : '<h3>Az aktuális szituáció mentetlen változásokat tartalmaz. </h3><h3>Ha a folytatást választja, a változások elvesznek. </h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Szélesség, hosszúság (tizedes fokok, például -118,15, 34,03)',
		'sim_scenario_usingFFgeolocation' : "A szituáció felületi elem nem támogatott Firefox alatt. ",
		'sim_scenario_usingIEgeolocation' : "A szituáció felületi elem nem támogatott Internet Explorer alatt. ",
		'sim_scenario_new' : 'Új',
		'sim_scenario_delete' : 'Törlés',
		'sim_scenario_delete_path' : 'Útvonal törlése',
		'sim_scenario_save' : 'Mentés',
		'sim_scenario_pause' : 'Szünet',
		'sim_scenario_play' : 'Lejátszás',
		'sim_scenario_restart' : 'Újraindítás',
		'sim_scenario_continue' : 'Folytatás',
		'sim_scenario_edit' : 'Szerkesztés',
		'sim_scenario_go' : 'Ugrás',
		'sim_scenario_cancel' : 'Mégse',
		'sim_scenario_export' : 'Exportálás',
		'sim_scenario_apply' : 'Alkalmazás',
		'sim_scenario_editor_name' : 'Név:',
		'sim_scenario_editor_name_textbox_placeholder' : 'Szituáció neve',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Szituáció neve</p>',
		'sim_scenario_editor_speed_label' : 'Sebesség (m/s)',
		'sim_scenario_editor_time_label' : 'Idő (másodperc)',
		'sim_scenario_editor_no_gps_zone_title' : 'GPS nélküli zóna',
		'sim_scenario_editor_access_point_title' : 'Hozzáférési pont',
		'sim_scenario_editor_route_point_title' : 'Útválasztási pont',
		'sim_scenario_editor_path_tooltip' : '<p>Mobileszköz szimulált elérési útjának létrehozása: </p>'+
												'<ul><li>Kattintson a térképre, ha csúcsokat (pontokat) kíván hozzáadni az útvonalhoz. </li><li>Kattintson duplán, ha befejezte. </li></ul>' +
												'<p>Az útvonal létrehozása után kattintson a csúcsra a mozgatásához vagy a tulajdonságainak szerkesztéséhez. </p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>WiFi zóna létrehozása: </p>'+
												'<ul><li>Az egér húzásával hozza létre a WiFi lefedettségi területét. </li></ul>' +
												'<p>A WiFi zóna létrehozása után kattintson a zónára a mozgatásához vagy a tulajdonságainak szerkesztéséhez. </p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>GPS lefedettség nélküli zóna létrehozása: </p>'+
												'<ul><li>Kattintson a térképre, ha csúcsokat (pontokat) kíván hozzáadni a zónához. </li><li>Kattintson duplán, ha befejezte. </li></ul>' +
												'<p>A GPS nélküli zóna létrehozása után kattintson a zónára a mozgatásához vagy a tulajdonságainak szerkesztéséhez. </p>'
});

