define({
		'sim_common_start' : '播放',
		'sim_common_stop' : '停止',
		'sim_common_error_button' : '生成错误',
		'sim_common_error_pending_button' : '错误暂挂',

		'sim_accelerometer_accelX_label' : 'X 轴：',
		'sim_accelerometer_accelY_label' : 'Y 轴：',
		'sim_accelerometer_accelZ_label' : 'Z 轴：',
		'sim_accelerometer_nextAccel_button' : '下一步',
		'sim_accelerometer_startStop_button' : '启动/停止',

		'sim_battery_plugedIn_label' : '插头位置：',
		'sim_battery_batteryLevel_label' : '电池级别：',

		'sim_battery_hrule_labels' : '0%、20%、40%、60%、80% 和 100%',

		'sim_camera_choose_image_camera' : '选择要用于相机的图像：',
		'sim_camera_currently_selected_camera' : '当前为相机选择的图像：',
		'sim_camera_choose_image_album_library' : '选择要用于相册/库的图像：',
		'sim_camera_currently_selected_album_library' : '当前为相册/库选择的图像：',
		'sim_camera_cannotLoadApplet' : "相机 API 模拟已禁用（未装入 applet，请检查 Java 设置）",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : '选择音频文件',
		'sim_capture_audio1' : '音频 1',
		'sim_capture_audio2' : '音频 2',
		'sim_capture_audio3' : '音频 3',
		'sim_capture_playAudio' : '播放',
		'sim_capture_choose_video' : '选择视频文件',
		'sim_capture_video1' : '视频 1',
		'sim_capture_video2' : '视频 2',
		'sim_capture_video3' : '视频 3',
		'sim_capture_playVideo' : '播放',
		'sim_capture_browserSupport' : '捕获模拟 UI 将与 Google Chrome 和 Mozilla Firefox 一起提供。',
		'sim_capture_cannotLoadApplet' : "捕获 API 模拟已禁用（未装入 applet，请检查 Java 设置）",
		'sim_compass_error_random' : '生成随机错误',
		'sim_compass_generate' : '生成',

		'sim_compass_heading_label' : '标题：',
		'sim_compass_next_button' : '下一步',
		'sim_compass_startStop_button' : '启动/停止',
		'sim_compass_error_button' : '生成错误',

		'sim_contacts_refresh_label' : '刷新',
		'sim_contacts_nowebsql' : 'Cordova 联系人 API 模拟已禁用，因为 WebSQL 在此浏览器中不受支持。',

		'sim_device_select_label' : '选择设备：',
		'sim_device_prev_button' : '上一个',
		'sim_device_next_button' : '下一个',
		'sim_device_no_version_info' : '没有任何版本信息',

		'sim_events_pause_button' : '暂停',
		'sim_events_resume_button' : '恢复',
		'sim_events_back_button' : '后退',
		'sim_events_menu_button' : '菜单',
		'sim_events_search_button' : '搜索',
		'sim_events_online_button' : '联机',
		'sim_events_offline_button' : '脱机',
		'sim_events_startCall_button' : '开始通话',
		'sim_events_endCall_button' : '结束通话',
		'sim_events_volumeUp_button' : '增大音量',
		'sim_events_volumeDown_button' : '减小音量',

		'sim_file_refresh_button' : "刷新",
		'sim_file_cannotLoadApplet' : "文件 API 模拟已禁用（未装入 applet，请检查 Java 设置）",
		'sim_geoloc_longitude_label' : '经度',
		'sim_geoloc_latitude_label' : '纬度',
		'sim_geoloc_accuracy_label' : '准确性',
		'sim_geoloc_altitude_label' : '海拔高度',
		'sim_geoloc_altitudeAccuracy_label' : '海拔高度准确性',
		'sim_geoloc_heading_label' : '标题',
		'sim_geoloc_velocity_label' : '速度 (m/s)',
		'sim_geoloc_next_button' : "步骤",
		'sim_geoloc_startStop_button' : "启动/停止",
		'sim_geoloc_usingFFgeolocation' : "使用 Firefox 所提供的地理位置服务。",
		'sim_geoloc_apply_tooltip' : "点击应用以使更改生效",
		'sim_geoloc_step_tooltip' : "根据标题每秒移动一次。",
		'sim_geoloc_startStop_tooltip' : "开始根据标题和速度移动。",

		'sim_media_url_label' : 'URL：',
		'sim_media_playBack_label' : '回放',
		'sim_media_length_label' : '长度',
		'sim_media_audioRecording_label' : '音频记录',
		'sim_media_audioRecording_status' : '空闲',
		'sim_media_audioRecording_idle' : '空闲',
		'sim_media_audioRecording_recording' : '正在记录',

		'sim_network_none' : '无',
		'sim_network_ethernet' : '以太网网络',
		'sim_network_wifi' : 'Wifi 网络',
		'sim_network_2g' : '2G 网络',
		'sim_network_3g' : '3G 网络',
		'sim_network_4g' : '4G 网络',
		'sim_network_cell' : '单元通用连接',
		'sim_network_unknown' : '未知网络',
		'sim_scenario_warning' : '警告',
		'sim_scenario_unsaved_text' : '<h3>当前方案中具有未保存的更改。</h3><h3>如果选择继续，将丢失那些更改。</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Latitude, Longitude （小数等级，例如 -118.15, 34.03）',
		'sim_scenario_usingFFgeolocation' : "此方案窗口小部件在 Firefox 中不受支持。",
		'sim_scenario_usingIEgeolocation' : "此方案窗口小部件在 Internet Explorer 中不受支持。",
		'sim_scenario_new' : '新建',
		'sim_scenario_delete' : '删除',
		'sim_scenario_delete_path' : '删除路径',
		'sim_scenario_save' : '保存',
		'sim_scenario_pause' : '暂停',
		'sim_scenario_play' : '播放',
		'sim_scenario_restart' : '重新启动',
		'sim_scenario_continue' : '继续',
		'sim_scenario_edit' : '编辑',
		'sim_scenario_go' : '执行',
		'sim_scenario_cancel' : '取消',
		'sim_scenario_export' : '导出',
		'sim_scenario_apply' : '应用',
		'sim_scenario_editor_name' : '名称：',
		'sim_scenario_editor_name_textbox_placeholder' : '方案名称',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">方案名称</p>',
		'sim_scenario_editor_speed_label' : '速度 (m/s)',
		'sim_scenario_editor_time_label' : '时间 (s)',
		'sim_scenario_editor_no_gps_zone_title' : '无 GPS 区域',
		'sim_scenario_editor_access_point_title' : '访问点',
		'sim_scenario_editor_route_point_title' : '路由点',
		'sim_scenario_editor_path_tooltip' : '<p>创建移动设备的模拟路径：</p>'+
												'<ul><li>单击映射已将顶点（点）添加到路径</li><li>完成时请双击</li></ul>' +
												'<p>在路径创建后，单击以移动该顶点或编辑其属性。</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>创建 WiFi 区域：</p>'+
												'<ul><li>拖动鼠标以创建 WiFi 覆盖区域。</li></ul>' +
												'<p>创建 WiFi 区域之后，单击以移动该区域或编辑其属性。</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>创建没有 GPS 覆盖的区域：</p>'+
												'<ul><li>单击映射以将顶点（点）添加到路径</li><li>完成时请双击</li></ul>' +
												'<p>创建无 GPS 区域之后，单击以移动该区域或编辑其属性。</p>'
});

