define({
		'sim_common_start' : 'تشغيل',
		'sim_common_stop' : 'ايقاف',
		'sim_common_error_button' : 'تكوين خطأ',
		'sim_common_error_pending_button' : 'خطأ معلق',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'التالي',
		'sim_accelerometer_startStop_button' : 'بدء / ايقاف',

		'sim_battery_plugedIn_label' : 'متصل:',
		'sim_battery_batteryLevel_label' : 'مستوى شحن البطارية:',

		'sim_battery_hrule_labels' : '0%،20%،40%،60%،80%،100%',

		'sim_camera_choose_image_camera' : 'اختر صورة لاستخدامها للكاميرا:',
		'sim_camera_currently_selected_camera' : 'الصورة المحددة حاليا للكاميرا:',
		'sim_camera_choose_image_album_library' : 'اختر صورة لاستخدامها للألبوم/المكتبة:',
		'sim_camera_currently_selected_album_library' : 'الصورة المحددة حاليا للألبوم/المكتبة:',
		'sim_camera_cannotLoadApplet' : "تم الغاء اتاحة محاكاة واجهة تعامل برمجة تطبيق الكاميرا (لم يتم تحميل برنامج applet، يرجى فحص محددات Java لديك)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'اختر ملف (ملفات) صوتى ',
		'sim_capture_audio1' : 'ملف صوتي 1',
		'sim_capture_audio2' : 'ملف صوتى 2',
		'sim_capture_audio3' : 'ملف صوتى 3',
		'sim_capture_playAudio' : 'تشغيل',
		'sim_capture_choose_video' : 'اختر ملف (ملفات) الفيديو ',
		'sim_capture_video1' : 'فيديو 1',
		'sim_capture_video2' : 'فيديو 2',
		'sim_capture_video3' : 'فيديو 3',
		'sim_capture_playVideo' : 'تشغيل',
		'sim_capture_browserSupport' : 'يتم اتاحة واجهة تعامل مستخدم محاكاة الالتقاط مع Google Chrome و Mozilla Firefox.',
		'sim_capture_cannotLoadApplet' : "تم الغاء اتاحة محاكاة واجهة تعامل برمجة تطبيق الالتقاط (لم يتم تحميل برنامج applet، يرجى فحص محددات Java لديك)",
		'sim_compass_error_random' : 'تكوين خطأ عشوائى',
		'sim_compass_generate' : 'تكوين',

		'sim_compass_heading_label' : 'العنوان:',
		'sim_compass_next_button' : 'التالي',
		'sim_compass_startStop_button' : 'بدء / ايقاف',
		'sim_compass_error_button' : 'تكوين خطأ',

		'sim_contacts_refresh_label' : 'تجديد',
		'sim_contacts_nowebsql' : 'ان محاكاة واجهة تعامل برمجة تطبيق جهات اتصال Cordova غير متاحة حيث أنه لا يتم دعم WebSQL فى برنامج الاستعراض هذا.',

		'sim_device_select_label' : 'تحديد جهاز:',
		'sim_device_prev_button' : 'السابق',
		'sim_device_next_button' : 'التالي',
		'sim_device_no_version_info' : 'لا توجد معلومات عن النسخة',

		'sim_events_pause_button' : 'ايقاف مؤقت',
		'sim_events_resume_button' : 'استكمال',
		'sim_events_back_button' : 'للخلف',
		'sim_events_menu_button' : 'قائمة',
		'sim_events_search_button' : 'بحث',
		'sim_events_online_button' : 'متصل',
		'sim_events_offline_button' : 'دون اتصال',
		'sim_events_startCall_button' : 'بدء الاتصال',
		'sim_events_endCall_button' : 'انهاء الاتصال',
		'sim_events_volumeUp_button' : 'رفع الصوت',
		'sim_events_volumeDown_button' : 'خفض الصوت',

		'sim_file_refresh_button' : "تجديد",
		'sim_file_cannotLoadApplet' : "تم الغاء اتاحة محاكاة واجهة تعامل برمجة تطبيق الملفات (لم يتم تحميل برنامج applet، يرجى فحص محددات Java لديك)",
		'sim_geoloc_longitude_label' : 'خط الطول',
		'sim_geoloc_latitude_label' : 'خط العرض',
		'sim_geoloc_accuracy_label' : 'الدقة',
		'sim_geoloc_altitude_label' : 'الارتفاع',
		'sim_geoloc_altitudeAccuracy_label' : 'دقة خط العرض',
		'sim_geoloc_heading_label' : 'العنوان',
		'sim_geoloc_velocity_label' : 'السرعة (متر/ثانية)',
		'sim_geoloc_next_button' : "خطوة",
		'sim_geoloc_startStop_button' : "تشغيل / ايقاف",
		'sim_geoloc_usingFFgeolocation' : "استخدام خدمة تحديد الموقع الجغرافي المتوفرة مع Firefox.",
		'sim_geoloc_apply_tooltip' : "اضغط تطبيق لكى يسرى مفعول التغييرات",
		'sim_geoloc_step_tooltip' : "تحرك مرة واحدة وفقا للعنوان والسرعة لكل 1 ثانية.",
		'sim_geoloc_startStop_tooltip' : "ابدأ الحركة وفقا للعنوان والسرعة.",

		'sim_media_url_label' : 'عنوان URL:',
		'sim_media_playBack_label' : 'استرجاع التسجيل',
		'sim_media_length_label' : 'الطول',
		'sim_media_audioRecording_label' : 'تسجيل صوتى',
		'sim_media_audioRecording_status' : 'بدون استخدام',
		'sim_media_audioRecording_idle' : 'بدون استخدام',
		'sim_media_audioRecording_recording' : 'تسجيل',

		'sim_network_none' : 'لا شيء',
		'sim_network_ethernet' : 'شبكة اتصال Ethernet',
		'sim_network_wifi' : 'شبكة اتصال Wifi',
		'sim_network_2g' : 'شبكة اتصال 2G',
		'sim_network_3g' : 'شبكة اتصال 3G',
		'sim_network_4g' : 'شبكة اتصال 4G',
		'sim_network_cell' : 'اتصال عام للخلية',
		'sim_network_unknown' : 'شبكة اتصال غير معروفة',
		'sim_scenario_warning' : 'تحذير',
		'sim_scenario_unsaved_text' : '<h3>لديك تغييرات لم يتم حفظها فى السيناريو الحالى.</h3><h3>اذا اخترت الاستمرار سوف تفقد هذه التغييرات.</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'خط العرض، خط الطول (درجات عشرية، على سبيل المثال -118.15، 34.03)',
		'sim_scenario_usingFFgeolocation' : "لا يتم دعم عنصر واجهة تعامل السيناريو فى Firefox.",
		'sim_scenario_usingIEgeolocation' : "لا يتم دعم عنصر واجهة تعامل السيناريو فى Internet Explorer.",
		'sim_scenario_new' : 'جديد',
		'sim_scenario_delete' : 'حذف',
		'sim_scenario_delete_path' : 'حذف المسار',
		'sim_scenario_save' : 'قم بالحفظ',
		'sim_scenario_pause' : 'ايقاف مؤقت',
		'sim_scenario_play' : 'تشغيل',
		'sim_scenario_restart' : 'اعادة بدء',
		'sim_scenario_continue' : 'الاستمرار',
		'sim_scenario_edit' : 'تحرير',
		'sim_scenario_go' : 'بدء',
		'sim_scenario_cancel' : 'الغاء',
		'sim_scenario_export' : 'تصدير',
		'sim_scenario_apply' : 'تطبيق',
		'sim_scenario_editor_name' : 'الاسم:',
		'sim_scenario_editor_name_textbox_placeholder' : 'اسم السيناريو',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">اسم السيناريو</p>',
		'sim_scenario_editor_speed_label' : 'السرعة (متر/ثانية)',
		'sim_scenario_editor_time_label' : 'الوقت (الأوقات)',
		'sim_scenario_editor_no_gps_zone_title' : 'لا يوجد نطاق نظام تحديد الموضع الشامل',
		'sim_scenario_editor_access_point_title' : 'نقطة التوصل',
		'sim_scenario_editor_route_point_title' : 'نقطة التوجيه',
		'sim_scenario_editor_path_tooltip' : '<p>تكوين مسار تم محاكاته لجهاز التليفون المحمول:</p>'+
												'<ul><li>اضغط على الخريطة لاضافة نقطة التقاطع (النقاط) الى المسار</li><li>اضغط مرتين عند الانتهاء</li></ul>' +
												'<p>بعد تكوين المسار، اضغط على نقطة التقاطع لنقلها أو تحرير خصائصها.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>تكوين نطاق WiFi:</p>'+
												'<ul><li>قم بسحي الفأرة لتكوين مساحة تغطية WiFi.</li></ul>' +
												'<p>بعد تكوين نطاق WiFi، اضغط على النطاق لنقله أو لتحرير خصائصه.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>تكوين نطاق بدون تغطية لنظام تحديد الموضع الشامل:</p>'+
												'<ul><li>اضغط على الخريطة لاضافة نقطة التقاطع (النقاط) الى النطاق</li><li>اضغط مرتين عند الانتهاء</li></ul>' +
												'<p>بعد تكوين نطاق بدون نظام تحديد الموضع الشامل، اضغط على النطاق لنقله أو لتحرير خصائصه.</p>'
});

