define({
		'sim_common_start' : '播放',
		'sim_common_stop' : '停止',
		'sim_common_error_button' : '產生錯誤',
		'sim_common_error_pending_button' : '錯誤擱置',

		'sim_accelerometer_accelX_label' : 'X：',
		'sim_accelerometer_accelY_label' : 'Y：',
		'sim_accelerometer_accelZ_label' : 'Z：',
		'sim_accelerometer_nextAccel_button' : '下一頁',
		'sim_accelerometer_startStop_button' : '開始/停止',

		'sim_battery_plugedIn_label' : '已接上電源：',
		'sim_battery_batteryLevel_label' : '剩餘電力：',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : '選擇要用於相機的影像：',
		'sim_camera_currently_selected_camera' : '目前給相機選取的影像：',
		'sim_camera_choose_image_album_library' : '選擇要用於相簿/程式庫的影像：',
		'sim_camera_currently_selected_album_library' : '目前給相簿/程式庫選取的影像：',
		'sim_camera_cannotLoadApplet' : "已停用相機 API 模擬（小應用程式未載入，請檢查 Java 設定）",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : '選擇音訊檔案',
		'sim_capture_audio1' : '音訊 1',
		'sim_capture_audio2' : '音訊 2',
		'sim_capture_audio3' : '音訊 3',
		'sim_capture_playAudio' : '播放',
		'sim_capture_choose_video' : '選擇視訊檔案',
		'sim_capture_video1' : '視訊 1',
		'sim_capture_video2' : '視訊 2',
		'sim_capture_video3' : '視訊 3',
		'sim_capture_playVideo' : '播放',
		'sim_capture_browserSupport' : '擷取模擬使用者介面適用於 Google Chrome 及 Mozilla Firefox。',
		'sim_capture_cannotLoadApplet' : "已停用擷取 API 模擬（小應用程式未載入，請檢查 Java 設定）",
		'sim_compass_error_random' : '產生隨機錯誤',
		'sim_compass_generate' : '產生',

		'sim_compass_heading_label' : '標題：',
		'sim_compass_next_button' : '下一頁',
		'sim_compass_startStop_button' : '開始/停止',
		'sim_compass_error_button' : '產生錯誤',

		'sim_contacts_refresh_label' : '重新整理',
		'sim_contacts_nowebsql' : '已停用 Cordova 聯絡人 API 模擬，因為此瀏覽器不支援 WebSQL。',

		'sim_device_select_label' : '選取裝置：',
		'sim_device_prev_button' : '上一頁',
		'sim_device_next_button' : '下一頁',
		'sim_device_no_version_info' : '沒有版本資訊',

		'sim_events_pause_button' : '暫停',
		'sim_events_resume_button' : '回復',
		'sim_events_back_button' : '向後',
		'sim_events_menu_button' : '功能表',
		'sim_events_search_button' : '搜尋',
		'sim_events_online_button' : '連線',
		'sim_events_offline_button' : '離線',
		'sim_events_startCall_button' : '開始通話',
		'sim_events_endCall_button' : '結束通話',
		'sim_events_volumeUp_button' : '提高音量',
		'sim_events_volumeDown_button' : '降低音量',

		'sim_file_refresh_button' : "重新整理",
		'sim_file_cannotLoadApplet' : "已停用檔案 API 模擬（未載入 Applet，請檢查 Java 設定）",
		'sim_geoloc_longitude_label' : '經度',
		'sim_geoloc_latitude_label' : '緯度',
		'sim_geoloc_accuracy_label' : '精確度',
		'sim_geoloc_altitude_label' : '高度',
		'sim_geoloc_altitudeAccuracy_label' : '高度精確度',
		'sim_geoloc_heading_label' : '標題',
		'sim_geoloc_velocity_label' : '速度 (m/s)',
		'sim_geoloc_next_button' : "步驟",
		'sim_geoloc_startStop_button' : "播放/停止",
		'sim_geoloc_usingFFgeolocation' : "使用 Firefox 提供的地理定位服務。",
		'sim_geoloc_apply_tooltip' : "按一下「套用」使變更生效。",
		'sim_geoloc_step_tooltip' : "依據標題和速度每秒移動一次。",
		'sim_geoloc_startStop_tooltip' : "依據標題和速度開始移動。",

		'sim_media_url_label' : 'URL：',
		'sim_media_playBack_label' : '播放',
		'sim_media_length_label' : '長度',
		'sim_media_audioRecording_label' : '音訊錄製',
		'sim_media_audioRecording_status' : '閒置',
		'sim_media_audioRecording_idle' : '閒置',
		'sim_media_audioRecording_recording' : '錄製',

		'sim_network_none' : '無',
		'sim_network_ethernet' : '乙太網路',
		'sim_network_wifi' : 'WiFi 網路',
		'sim_network_2g' : '2G 網路',
		'sim_network_3g' : '3G 網路',
		'sim_network_4g' : '4G 網路',
		'sim_network_cell' : '資料格一般連線',
		'sim_network_unknown' : '不明網路',
		'sim_scenario_warning' : '警告',
		'sim_scenario_unsaved_text' : '<h3>您沒有將變更儲存到現行實務範例中。</h3><h3>如果選擇繼續，變更將會丟失。</h3>',
		'sim_scenario_editor_go_input_placeholder' : '經度、緯度（十進制，例如 -118.15, 34.03）',
		'sim_scenario_usingFFgeolocation' : "Firefox 不支援實務範例小組件。",
		'sim_scenario_usingIEgeolocation' : "Internet Explorer 不支援實務範例小組件。",
		'sim_scenario_new' : '新建',
		'sim_scenario_delete' : '刪除',
		'sim_scenario_delete_path' : '刪除路徑',
		'sim_scenario_save' : '儲存',
		'sim_scenario_pause' : '暫停',
		'sim_scenario_play' : '播放',
		'sim_scenario_restart' : '重新啟動',
		'sim_scenario_continue' : '繼續',
		'sim_scenario_edit' : '編輯',
		'sim_scenario_go' : '執行',
		'sim_scenario_cancel' : '取消',
		'sim_scenario_export' : '匯出',
		'sim_scenario_apply' : '套用',
		'sim_scenario_editor_name' : '名稱：',
		'sim_scenario_editor_name_textbox_placeholder' : '實務範例名稱',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">實務範例名稱</p>',
		'sim_scenario_editor_speed_label' : '速度 (m/s)',
		'sim_scenario_editor_time_label' : '時間 (s)',
		'sim_scenario_editor_no_gps_zone_title' : '沒有 GPS 區域',
		'sim_scenario_editor_access_point_title' : '存取點',
		'sim_scenario_editor_route_point_title' : '路徑點',
		'sim_scenario_editor_path_tooltip' : '<p>建立行動式裝置的模擬路徑：</p>'+
												'<ul><li>按一下對映以將頂點（點）新增至此路徑</li><li>完成時按兩下</li></ul>' +
												'<p>建立路徑之後，按一下此頂點進行移動或編輯其內容。</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>建立 WiFi 區域：</p>'+
												'<ul><li>拖曳滑鼠來建立 WiFi 涵蓋面區域。</li></ul>' +
												'<p>建立 WiFi 區域之後，按一下此區域進行移動或編輯其內容。</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>建立不具有 GPS 涵蓋面的區域：</p>'+
												'<ul><li>按一下對映以將頂點（點）新增至此區域</li><li>完成時按兩下</li></ul>' +
												'<p>建立不具有 GPS 的區域之後，按一下此區域進行移動或編輯其內容。</p>'
});

