define({
		'sim_common_start' : '재생',
		'sim_common_stop' : '중지',
		'sim_common_error_button' : '생성 오류',
		'sim_common_error_pending_button' : '중지 오류',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : '다음',
		'sim_accelerometer_startStop_button' : '시작 / 중지',

		'sim_battery_plugedIn_label' : '플러그인:',
		'sim_battery_batteryLevel_label' : '배터리 레벨:',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : '카메라에 사용할 이미지 선택:',
		'sim_camera_currently_selected_camera' : '카메라에 현재 선택된 이미지:',
		'sim_camera_choose_image_album_library' : '앨범/라이브러리에 사용할 이미지 선택:',
		'sim_camera_currently_selected_album_library' : '앨범/라이브러리에 대해 현재 선택된 이미지',
		'sim_camera_cannotLoadApplet' : "카메라 API 시뮬레이션이 사용 불가능함(애플릿이 로드되지 않았습니다. Java 설정을 확인하십시오.)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : '오디오 파일 선택',
		'sim_capture_audio1' : '오디오 1',
		'sim_capture_audio2' : '오디오 2',
		'sim_capture_audio3' : '오디오 3',
		'sim_capture_playAudio' : '재생',
		'sim_capture_choose_video' : '비디오 파일 선택',
		'sim_capture_video1' : '비디오 1',
		'sim_capture_video2' : '비디오 2',
		'sim_capture_video3' : '비디오 3',
		'sim_capture_playVideo' : '재생',
		'sim_capture_browserSupport' : 'Google Chrome 및 Mozilla Firefox로 캡처 시뮬레이션 UI를 사용할 수 있습니다. ',
		'sim_capture_cannotLoadApplet' : "캡처 API 시뮬레이션이 사용 불가능함(애플릿이 로드되지 않았습니다. Java 설정을 확인하십시오.)",
		'sim_compass_error_random' : '랜덤 오류 생성',
		'sim_compass_generate' : '생성',

		'sim_compass_heading_label' : '표제:',
		'sim_compass_next_button' : '다음',
		'sim_compass_startStop_button' : '시작 / 중지',
		'sim_compass_error_button' : '생성 오류',

		'sim_contacts_refresh_label' : '새로 고치기',
		'sim_contacts_nowebsql' : 'WebSQL은 이 브라우저에서 지원되지 않으므로 Cordova 접속 API 시뮬레이션이 사용되지 않습니다. ',

		'sim_device_select_label' : '디바이스 선택:',
		'sim_device_prev_button' : '이전',
		'sim_device_next_button' : '다음',
		'sim_device_no_version_info' : '버전 정보가 없음',

		'sim_events_pause_button' : '일시정지',
		'sim_events_resume_button' : '재개',
		'sim_events_back_button' : '이전',
		'sim_events_menu_button' : '메뉴',
		'sim_events_search_button' : '검색',
		'sim_events_online_button' : '온라인',
		'sim_events_offline_button' : '오프라인',
		'sim_events_startCall_button' : '호출 시작',
		'sim_events_endCall_button' : '호출 종료',
		'sim_events_volumeUp_button' : '볼륨 높이기',
		'sim_events_volumeDown_button' : '볼륨 줄이기',

		'sim_file_refresh_button' : "새로 고치기",
		'sim_file_cannotLoadApplet' : "파일 API 시뮬레이션이 사용 불가능함(애플릿이 로드되지 않았습니다. Java 설정을 확인하십시오.)",
		'sim_geoloc_longitude_label' : '경도',
		'sim_geoloc_latitude_label' : '위도',
		'sim_geoloc_accuracy_label' : '정확도',
		'sim_geoloc_altitude_label' : '고도',
		'sim_geoloc_altitudeAccuracy_label' : '고도 정확도',
		'sim_geoloc_heading_label' : '표제',
		'sim_geoloc_velocity_label' : '속도(m/s)',
		'sim_geoloc_next_button' : "단계",
		'sim_geoloc_startStop_button' : "재생 / 중지",
		'sim_geoloc_usingFFgeolocation' : "Firefox로 제공된 지위위치 서비스 사용",
		'sim_geoloc_apply_tooltip' : "변경을 적용하려면 적용을 누르십시오.",
		'sim_geoloc_step_tooltip' : "1초마다 표제 및 속도에 따라 한 번 이동하십시오.",
		'sim_geoloc_startStop_tooltip' : "표제 및 속도에 따라 이동을 시작하십시오.",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : '재생',
		'sim_media_length_label' : '길이',
		'sim_media_audioRecording_label' : '오디오 레코딩',
		'sim_media_audioRecording_status' : '유휴',
		'sim_media_audioRecording_idle' : '유휴',
		'sim_media_audioRecording_recording' : '레코딩',

		'sim_network_none' : '없음',
		'sim_network_ethernet' : '이더넷 네트워크',
		'sim_network_wifi' : 'Wifi 네트워크',
		'sim_network_2g' : '2G 네트워크',
		'sim_network_3g' : '3G 네트워크',
		'sim_network_4g' : '4G 네트워크',
		'sim_network_cell' : '셀 일반 연결',
		'sim_network_unknown' : '알 수 없는 네트워크',
		'sim_scenario_warning' : '경고',
		'sim_scenario_unsaved_text' : '<h3>현재 시나리오에서 저장되지 않은 변경사항이 있습니다.</h3><h3>계속하도록 선택하면 해당 변경사항은 유실됩니다.</h3>',
		'sim_scenario_editor_go_input_placeholder' : '위도, 경도(10진수, 예제: -118.15, 34.03)',
		'sim_scenario_usingFFgeolocation' : "Firefox에서는 시나리오 위젯이 지원되지 않습니다.",
		'sim_scenario_usingIEgeolocation' : "Internet Explorer에서는 시나리오 위젯이 지원되지 않습니다.",
		'sim_scenario_new' : '새로 작성',
		'sim_scenario_delete' : '삭제',
		'sim_scenario_delete_path' : '경로 삭제',
		'sim_scenario_save' : '저장',
		'sim_scenario_pause' : '일시정지',
		'sim_scenario_play' : '재생',
		'sim_scenario_restart' : '다시 시작',
		'sim_scenario_continue' : '계속',
		'sim_scenario_edit' : '편집',
		'sim_scenario_go' : '이동',
		'sim_scenario_cancel' : '취소 ',
		'sim_scenario_export' : '내보내기',
		'sim_scenario_apply' : '적용',
		'sim_scenario_editor_name' : '이름:',
		'sim_scenario_editor_name_textbox_placeholder' : '시나리오 이름',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">시나리오 이름</p>',
		'sim_scenario_editor_speed_label' : '속도(m/s)',
		'sim_scenario_editor_time_label' : '시간(초)',
		'sim_scenario_editor_no_gps_zone_title' : 'GPS 구역 없음',
		'sim_scenario_editor_access_point_title' : '액세스 지점',
		'sim_scenario_editor_route_point_title' : '라우트 지점',
		'sim_scenario_editor_path_tooltip' : '<p>시뮬레이션된 모바일 디바이스의 경로 작성:</p>'+
												'<ul><li>맵을 클릭하여 경로에 정점 추가</li><li>완료 시 두 번 클릭</li></ul>' +
												'<p>경로를 작성한 후 정점을 클릭하여 이동하거나 특성을 편집하십시오.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>와이파이 구역 작성:</p>'+
												'<ul><li>마우스를 끌어 와이파이 적용 영역을 작성하십시오.</li></ul>' +
												'<p>와이파이 구역을 작성한 후 구역을 클릭하여 이동하거나 특성을 편집하십시오.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>GPS가 적용되지 않는 구역 작성:</p>'+
												'<ul><li>맵을 클릭하여 구역에 정점 추가</li><li>완료 시 두 번 클릭</li></ul>' +
												'<p>GPS 구역 없음을 작성한 후 구역을 클릭하여 이동하거나 특성을 편집하십시오.</p>'
});

