//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'A visualização de páginas da web que não estejam no servidor do cliente de teste causará uma redução significativa na função do cliente de teste.',

	'index_title' : 'Simulador de Navegador Remoto',
	'index_desc' : 'O Simulador de Navegador Remoto exibe páginas de web remotas em uma variedade de tamanhos e formas do navegador remoto.',
	'index_webpage' : 'Página da Web:',
	'index_go' : 'Ir / Atualizar',
	'index_go_simple_preview' : 'Abrir Visualização Simples',
	'index_scale' : 'Escalar Todos os Dispositivos:',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'Ajustar à janela',
	'index_scale_physical' : 'Tamanho do dispositivo físico',
	'index_add_device' : 'Incluir Dispositivo',
	'index_calibrate' : 'Calibrar Tamanho Físico',
	'index_calibrate_dialog_title' : 'Calibração do Tamanho Físico',
	'index_scaling_warning' : 'O Simulador de Navegador Remoto não suporta ajuste de escala do conteúdo neste navegador. O Simulador de Navegador Remoto suporta ajuste de escala de conteúdo na versão mais recente do Mozilla Firefox ou do Internet Explorer 9 e superior.',
	'index_xdomain_warning' : 'A página da web exibida atualmente está em um servidor diferente do servidor deste cliente de teste.',
	'index_enable_useragent_switching' : 'Ativar a Comutação do Useragent',
	'index_useragent_switching_desc' : 'A comutação do ID do Useragent permite que o simulador altere o ID do useragent no navegador, de forma que quando uma página for carregada no simulador, a página requeira o uso da sequência correta do ID do useragent.',
	'index_useragent_switching_support' : 'A comutação do Useragent é suportada nos seguintes navegadores:',
	'index_useragent_extension_install_title' : 'Instale a Extensão do Comutador Useragent',
	'index_useragent_extension_install_instructions_1' : 'Para que o Simulador de Navegador Remoto alterne automaticamente a sequência do ID de useragent, uma extensão deve ser instalada no navegador.',
	'index_useragent_extension_install_instructions_2' : 'O Simulador detecta se uma versão atual da extensão não estiver instalada. Use o link abaixo para instalar a extensão mais recente para o navegador atual.',
	'index_useragent_extension_install_btn' : 'Instale a Extensão do Navegador',
	'index_useragent_extension_install_instructions_chrome1' : 'Nota: Se depois de tentar instalar a extensão, você tiver a seguinte mensagem \"Extensões, aplicativos e scripts de usuário só podem ser incluídos do Chrome Web Store.\", então você precisa instalar manualmente a extensão. Aqui estão as etapas para seguir:',
	'index_useragent_extension_install_instructions_chrome2' : 'Abra as configurações do Chrome',
	'index_useragent_extension_install_instructions_chrome3' : 'Vá para a página de extensão do Chrome',
	'index_useragent_extension_install_instructions_chrome4' : 'Arraste e solte o arquivo de extensão transferido por download da barra de ferramentas de download para a página de extensões',
	'index_need_http' : "Ao usar um caminho não relativo, 'http://' deve ser pré-anexado ao caminho.",
	'index_splash_title' : "Carregando...",
	'index_splash_status' : "O simulador estará pronto em um instante.",	
	'MobileDeviceTree_by_platform' : 'Por plataforma',
	'MobileDeviceTree_by_resolution' : 'Por resolução',
	'MobileDeviceTree_platforms' : 'Plataformas',
	'MobileDeviceTree_resolutions' : 'Resoluções',
	'MobileBrowserSimulator_rotate' : 'Girar',
	'MobileBrowserSimulator_remove_device': 'Remover Dispositivo',
	'MobileBrowserSimulator_xdomain_warning' : 'A página da web exibida atualmente está em um servidor diferente do servidor deste cliente de teste.',
	'MobileBrowserSimulator_skin' : 'Capa',
	'QRCodeTooltip' : 'Varra esse QRCode para carregar a página da web simulada em seu próprio dispositivo móvel.',
	'QRCodeIPTooltip' : 'Você tem que escolher/inserir o IP ou nome do host que será usado para acessar a página da web simulada a partir de seu próprio dispositivo móvel.',
	'QRCodeIPHostName' : 'IP/Nome do Host',
	'PPICalculator_desc' : 'Para visualizar a página em execução no simulador no tamanho físico dos vários dispositivos remotos, o simulador precisa ser calibrado para o monitor atual:',
	'PPICalculator_step_1' : 'Posicione um cartão de crédito de tamanho padrão na tela, de forma que a parte superior do cartão fique alinhada com a linha sólida preta.',
	'PPICalculator_step_2' : 'Arraste a linha cinza pontilhada ou use as teclas de seta para alinhar com a parte inferior do cartão.',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "A versão atual de seu navegador da web não é totalmente suportada.",
	'Downgrade' : "Você deve fazer downgrade para",
	'Upgrade' : "Você deve fazer upgrade para",
	'OrLater' : "ou mais recente",
	'Firefox_version_warning' : "A alternância de agente do usuário por dispositivo não é suportada no Firefox versões 17-22.",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "Simular API do dispositivo",
	'index_cordova_enable_desc' : 'Ativar a simulação do Apache Cordova API.',	
	'index_cordova_support' : 'A simulação do Apache Cordova é suportada pelos ambientes Android, iPhone, iPad, Windows Phone, Windows 8 e BlackBerry 10 e está disponível apenas nos navegadores a seguir:'

//end v1.x content
});

