define({
		'sim_common_start' : 'Воспроизведение',
		'sim_common_stop' : 'Стоп',
		'sim_common_error_button' : 'Сгенерировать ошибку',
		'sim_common_error_pending_button' : 'Ожидание ошибки',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'Далее',
		'sim_accelerometer_startStop_button' : 'Пуск/стоп',

		'sim_battery_plugedIn_label' : 'Питание от сети:',
		'sim_battery_batteryLevel_label' : 'Уровень заряда батареи:',

		'sim_battery_hrule_labels' : '0 %,20 %,40 %,60 %,80 %,100 %',

		'sim_camera_choose_image_camera' : 'Выберите изображение для камеры:',
		'sim_camera_currently_selected_camera' : 'Текущее изображение для камеры:',
		'sim_camera_choose_image_album_library' : 'Выберите изображение для альбома/библиотеки:',
		'sim_camera_currently_selected_album_library' : 'Текущее изображение для альбома/библиотеки:',
		'sim_camera_cannotLoadApplet' : "Имитация API камеры выключена (аплет не загружен; проверьте свои параметры Java)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Выберите аудиофайлы',
		'sim_capture_audio1' : 'Аудио 1',
		'sim_capture_audio2' : 'Аудио 2',
		'sim_capture_audio3' : 'Аудио 3',
		'sim_capture_playAudio' : 'Воспроизведение',
		'sim_capture_choose_video' : 'Выберите видеофайлы',
		'sim_capture_video1' : 'Видео 1',
		'sim_capture_video2' : 'Видео 2',
		'sim_capture_video3' : 'Видео 3',
		'sim_capture_playVideo' : 'Воспроизведение',
		'sim_capture_browserSupport' : 'Пользовательский интерфейс имитации записи доступен в браузерах Google Chrome и Mozilla Firefox.',
		'sim_capture_cannotLoadApplet' : "Имитация API захвата выключена (аплет не загружен; проверьте свои параметры Java)",
		'sim_compass_error_random' : 'Сгенерировать случайную ошибку',
		'sim_compass_generate' : 'Сгенерировать',

		'sim_compass_heading_label' : 'Заголовок:',
		'sim_compass_next_button' : 'Далее',
		'sim_compass_startStop_button' : 'Пуск/стоп',
		'sim_compass_error_button' : 'Сгенерировать ошибку',

		'sim_contacts_refresh_label' : 'Обновить',
		'sim_contacts_nowebsql' : 'Имитация API контактов Cordova выключена, так как данный браузер не поддерживает WebSQL.',

		'sim_device_select_label' : 'Выберите устройство:',
		'sim_device_prev_button' : 'Назад',
		'sim_device_next_button' : 'Далее',
		'sim_device_no_version_info' : 'Нет информации о версии',

		'sim_events_pause_button' : 'Прервать',
		'sim_events_resume_button' : 'Возобновить',
		'sim_events_back_button' : 'Назад',
		'sim_events_menu_button' : 'Меню',
		'sim_events_search_button' : 'Поиск',
		'sim_events_online_button' : 'Подключен',
		'sim_events_offline_button' : 'Без подключения',
		'sim_events_startCall_button' : 'Начать вызов',
		'sim_events_endCall_button' : 'Завершить вызов',
		'sim_events_volumeUp_button' : 'Увеличить громкость',
		'sim_events_volumeDown_button' : 'Уменьшить громкость',

		'sim_file_refresh_button' : "Обновить",
		'sim_file_cannotLoadApplet' : "Имитация API файла выключена (аплет не загружен; проверьте свои параметры Java)",
		'sim_geoloc_longitude_label' : 'Долгота',
		'sim_geoloc_latitude_label' : 'Широта',
		'sim_geoloc_accuracy_label' : 'Точность',
		'sim_geoloc_altitude_label' : 'Высота',
		'sim_geoloc_altitudeAccuracy_label' : 'Точность измерения высоты',
		'sim_geoloc_heading_label' : 'Заголовок',
		'sim_geoloc_velocity_label' : 'Скорость (м/с)',
		'sim_geoloc_next_button' : "Шаг",
		'sim_geoloc_startStop_button' : "Воспроизвести/остановить",
		'sim_geoloc_usingFFgeolocation' : "Через службу геолокации браузера Firefox.",
		'sim_geoloc_apply_tooltip' : "Нажмите Применить, чтобы изменения вступили в силу",
		'sim_geoloc_step_tooltip' : "Перемещать раз в секунду в соответствии с заголовком и скоростью.",
		'sim_geoloc_startStop_tooltip' : "Начать перемещение в соответствии с заголовком и скоростью.",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : 'Воспроизведение',
		'sim_media_length_label' : 'Длина',
		'sim_media_audioRecording_label' : 'Запись аудио',
		'sim_media_audioRecording_status' : 'Простой',
		'sim_media_audioRecording_idle' : 'Простой',
		'sim_media_audioRecording_recording' : 'Запись',

		'sim_network_none' : 'Нет',
		'sim_network_ethernet' : 'Сеть Ethernet',
		'sim_network_wifi' : 'Сеть Wi-Fi',
		'sim_network_2g' : 'Сеть 2G',
		'sim_network_3g' : 'Сеть 3G',
		'sim_network_4g' : 'Сеть 4G',
		'sim_network_cell' : 'Обычное мобильное соединение',
		'sim_network_unknown' : 'Неизвестная сеть',
		'sim_scenario_warning' : 'Предупреждение',
		'sim_scenario_unsaved_text' : '<h3>В текущем сценарии есть несохраненные изменения.</h3><h3>В случае продолжения эти изменения будут утеряны.</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Ширина, долгота (в градусах с точностью до десятых долей, например 118,15, 34,03)',
		'sim_scenario_usingFFgeolocation' : "Виджет сценария не поддерживается в Firefox.",
		'sim_scenario_usingIEgeolocation' : "Виджет сценария не поддерживается в Internet Explorer.",
		'sim_scenario_new' : 'Создать',
		'sim_scenario_delete' : 'Удалить',
		'sim_scenario_delete_path' : 'Удалить путь',
		'sim_scenario_save' : 'Сохранить',
		'sim_scenario_pause' : 'Прервать',
		'sim_scenario_play' : 'Воспроизведение',
		'sim_scenario_restart' : 'Перезапустить',
		'sim_scenario_continue' : 'Продолжить',
		'sim_scenario_edit' : 'Изменить',
		'sim_scenario_go' : 'Перейти',
		'sim_scenario_cancel' : 'Отмена',
		'sim_scenario_export' : 'Экспортировать',
		'sim_scenario_apply' : 'Применить',
		'sim_scenario_editor_name' : 'Имя:',
		'sim_scenario_editor_name_textbox_placeholder' : 'Имя сценария',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Имя сценария</p>',
		'sim_scenario_editor_speed_label' : 'Скорость (м/с)',
		'sim_scenario_editor_time_label' : 'Время (с)',
		'sim_scenario_editor_no_gps_zone_title' : 'Нет сигнала GPS',
		'sim_scenario_editor_access_point_title' : 'Точка доступа',
		'sim_scenario_editor_route_point_title' : 'Точка на маршруте',
		'sim_scenario_editor_path_tooltip' : '<p>Сымитировать путь мобильного устройства:</p>'+
												'<ul><li>Щелкните на карте для добавления узлов (точек) пути</li><li>Дважды щелкните, когда все будет готово</li></ul>' +
												'<p>Для перемещения узла или изменения его свойств после создания пути щелкните на этом узле.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>Создать зону Wi-Fi:</p>'+
												'<ul><li>Переместите курсор мыши для создания зоны покрытия Wi-Fi.</li></ul>' +
												'<p>Щелкните на созданной зоне Wi-Fi, чтобы переместить ее или изменить ее свойства.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>Создать зону без покрытия GPS:</p>'+
												'<ul><li>Щелкните на карте, чтобы добавить узлы (точки) зоны</li><li>Дважды щелкните, когда все будет готово</li></ul>' +
												'<p>Щелкните на созданной зоне без GPS, чтобы переместить ее или изменить ее свойства.</p>'
});

