define({
		'sim_common_start' : 'Přehrát',
		'sim_common_stop' : 'Zastavit',
		'sim_common_error_button' : 'Generovat chybu',
		'sim_common_error_pending_button' : 'Nevyřízená chyba',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'Další',
		'sim_accelerometer_startStop_button' : 'Spustit / Zastavit',

		'sim_battery_plugedIn_label' : 'Zapojeno:',
		'sim_battery_batteryLevel_label' : 'Úroveň baterie:',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : 'Vyberte obrázek, který se má použít pro fotoaparát:',
		'sim_camera_currently_selected_camera' : 'Aktuálně vybraný obrázek pro fotoaparát:',
		'sim_camera_choose_image_album_library' : 'Zvolte obrázek k použití pro album/knihovnu:',
		'sim_camera_currently_selected_album_library' : 'Momentálně vybraný obrázek pro album/knihovnu:',
		'sim_camera_cannotLoadApplet' : "Simulace rozhraní API kamery je vypnuta (aplet není načtený, zkontrolujte prosím nastavení Java)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Vyberte audio soubor(y)',
		'sim_capture_audio1' : 'Audio 1',
		'sim_capture_audio2' : 'Audio 2',
		'sim_capture_audio3' : 'Audio 3',
		'sim_capture_playAudio' : 'Přehrát',
		'sim_capture_choose_video' : 'Vybrat video soubor(y)',
		'sim_capture_video1' : 'Video 1',
		'sim_capture_video2' : 'Video 2',
		'sim_capture_video3' : 'Video 3',
		'sim_capture_playVideo' : 'Přehrát',
		'sim_capture_browserSupport' : 'UI simulace zachycení dat je k dispozici v prohlížeči Google Chrome a Mozilla Firefox.',
		'sim_capture_cannotLoadApplet' : "Simulace rozhraní API zachycení je vypnuta (aplet není načtený, zkontrolujte prosím nastavení Java)",
		'sim_compass_error_random' : 'Generovat náhodnou chybu',
		'sim_compass_generate' : 'Generovat',

		'sim_compass_heading_label' : 'Záhlaví:',
		'sim_compass_next_button' : 'Další',
		'sim_compass_startStop_button' : 'Spustit / Zastavit',
		'sim_compass_error_button' : 'Generovat chybu',

		'sim_contacts_refresh_label' : 'Obnovit',
		'sim_contacts_nowebsql' : 'Simulace rozhraní API kontaktů Cordova je zakázána, protože WebSQL není podporován v tomto prohlížeči.',

		'sim_device_select_label' : 'Vybrat zařízení:',
		'sim_device_prev_button' : 'Předchozí',
		'sim_device_next_button' : 'Další',
		'sim_device_no_version_info' : 'Žádné informace o verzi',

		'sim_events_pause_button' : 'Pozastavit',
		'sim_events_resume_button' : 'Obnovit',
		'sim_events_back_button' : 'Zpět',
		'sim_events_menu_button' : 'Nabídka',
		'sim_events_search_button' : 'Hledat',
		'sim_events_online_button' : 'Online',
		'sim_events_offline_button' : 'Offline',
		'sim_events_startCall_button' : 'Spustit volání',
		'sim_events_endCall_button' : 'Ukončit volání',
		'sim_events_volumeUp_button' : 'Zvýšit hlasitost',
		'sim_events_volumeDown_button' : 'Snížit hlasitost',

		'sim_file_refresh_button' : "Obnovit",
		'sim_file_cannotLoadApplet' : "Simulace rozhraní API souboru je vypnuta (aplet není načtený, zkontrolujte prosím nastavení Java)",
		'sim_geoloc_longitude_label' : 'Zeměpisná délka',
		'sim_geoloc_latitude_label' : 'Zeměpisná šířka',
		'sim_geoloc_accuracy_label' : 'Přesnost',
		'sim_geoloc_altitude_label' : 'Nadmořská výška',
		'sim_geoloc_altitudeAccuracy_label' : 'Přesnost nadmořské výšky',
		'sim_geoloc_heading_label' : 'Záhlaví',
		'sim_geoloc_velocity_label' : 'Rychlost (m/s)',
		'sim_geoloc_next_button' : "Krok",
		'sim_geoloc_startStop_button' : "Přehrát / Zastavit",
		'sim_geoloc_usingFFgeolocation' : "Použití služby geolokace poskytnuté prohlížečem Firefox.",
		'sim_geoloc_apply_tooltip' : "Stisknutím tlačítka Použít se projeví změny",
		'sim_geoloc_step_tooltip' : "Přesuňte se jednou dle záhlaví a rychlosti za sekundu.",
		'sim_geoloc_startStop_tooltip' : "Spusťte přesunutí dle záhlaví a rychlosti.",

		'sim_media_url_label' : 'Adresa URL:',
		'sim_media_playBack_label' : 'Přehrát znovu',
		'sim_media_length_label' : 'Délka',
		'sim_media_audioRecording_label' : 'Zvukový záznam',
		'sim_media_audioRecording_status' : 'Nečinný',
		'sim_media_audioRecording_idle' : 'Nečinný',
		'sim_media_audioRecording_recording' : 'Záznam',

		'sim_network_none' : 'Žádný',
		'sim_network_ethernet' : 'Síť Ethernet',
		'sim_network_wifi' : 'Síť wifi',
		'sim_network_2g' : 'Síť 2G',
		'sim_network_3g' : 'Síť 3G',
		'sim_network_4g' : 'Síť 4G',
		'sim_network_cell' : 'Generické připojení buňky',
		'sim_network_unknown' : 'Neznámá síť',
		'sim_scenario_warning' : 'Varování',
		'sim_scenario_unsaved_text' : '<h3>V aktuálním scénáři máte neuložené změny.</h3><h3>Pokud budete pokračovat, tyto změny se ztratí.</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Zeměpisná šířka, zeměpisná délka (desetinné stupně, například -118.15, 34.03)',
		'sim_scenario_usingFFgeolocation' : "Modul widget scénáře není podporován v prohlížeči Firefox.",
		'sim_scenario_usingIEgeolocation' : "Modul widget scénáře není podporován v prohlížeči Internet Explorer.",
		'sim_scenario_new' : 'Nový',
		'sim_scenario_delete' : 'Odstranit',
		'sim_scenario_delete_path' : 'Odstranit cestu',
		'sim_scenario_save' : 'Uložit',
		'sim_scenario_pause' : 'Pozastavit',
		'sim_scenario_play' : 'Přehrát',
		'sim_scenario_restart' : 'Restartovat',
		'sim_scenario_continue' : 'Pokračovat',
		'sim_scenario_edit' : 'Upravit',
		'sim_scenario_go' : 'Spustit',
		'sim_scenario_cancel' : 'Storno',
		'sim_scenario_export' : 'Exportovat',
		'sim_scenario_apply' : 'Použít',
		'sim_scenario_editor_name' : 'Název:',
		'sim_scenario_editor_name_textbox_placeholder' : 'Název scénáře',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Název scénáře</p>',
		'sim_scenario_editor_speed_label' : 'Rychlost (m/s)',
		'sim_scenario_editor_time_label' : 'Čas (s)',
		'sim_scenario_editor_no_gps_zone_title' : 'Bez zóny GPS',
		'sim_scenario_editor_access_point_title' : 'Přístupový bod',
		'sim_scenario_editor_route_point_title' : 'Směrovací bod',
		'sim_scenario_editor_path_tooltip' : '<p>Vytvořte simulovanou cestu mobilního zařízení:</p>'+
												'<ul><li>Klepnutím na tlačítko Mapovat přidáte vrcholy (body) do cesty</li><li>Při dokončení poklepejte</li></ul>' +
												'<p>Po vytvoření cesty klepněte na vrchol pro jeho přesunutí nebo úpravu vlastností.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>Vytvořte zónu WiFi:</p>'+
												'<ul><li>Přetažením myši vytvoříte oblast pokrytí zóny WiFi.</li></ul>' +
												'<p>Po vytvoření zóny WiFi klepněte na zónu pro její přesunutí nebo úpravu vlastností.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>Vytvořte zónu bez pokrytí GPS:</p>'+
												'<ul><li>Klepnutím na tlačítko Mapovat přidáte vrcholy (body) do zóny</li><li>Při dokončení poklepejte</li></ul>' +
												'<p>Po vytvoření zóny bez GPS klepněte na zónu pro její přesunutí nebo úpravu vlastností.</p>'
});

