//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'テスト・クライアント・サーバー上にない Web ページを表示すると、テスト・クライアントの機能が大きく低下する結果になります。',

	'index_title' : 'モバイル・ブラウザー・シミュレーター',
	'index_desc' : 'モバイル・ブラウザー・シミュレーターは、モバイル Web ページをさまざまなモバイル・ブラウザーのサイズや形状で表示します。',
	'index_webpage' : 'Web ページ:',
	'index_go' : '実行 / 更新',
	'index_go_simple_preview' : 'シンプル・プレビューを開く',
	'index_scale' : '全デバイスをスケール:',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'ウィンドウに合わせる',
	'index_scale_physical' : '物理デバイス・サイズ',
	'index_add_device' : 'デバイスの追加',
	'index_calibrate' : '物理サイズの調整',
	'index_calibrate_dialog_title' : '物理サイズの調整',
	'index_scaling_warning' : 'モバイル・ブラウザー・シミュレーターは、このブラウザーでのコンテンツのスケーリングをサポートしていません。モバイル・ブラウザー・シミュレーターは、Mozilla Firefox の最新バージョンまたは Internet Explorer 9 以上でコンテンツのスケーリングをサポートしています。',
	'index_xdomain_warning' : '現在表示されている Web ページは、このテスト・クライアントと異なるサーバーにあります。',
	'index_enable_useragent_switching' : 'ユーザー・エージェントの切り替えを有効にする',
	'index_useragent_switching_desc' : 'ユーザー・エージェント ID を切り替えることで、シミュレーターでブラウザー内のユーザー・エージェント ID が変更できます。これにより、ページをシミュレーターに読み込むと、正しいユーザー・エージェント ID ストリングを使用してページが要求されます。',
	'index_useragent_switching_support' : 'ユーザー・エージェントの切り替えがサポートされるブラウザー:',
	'index_useragent_extension_install_title' : 'ユーザー・エージェント切り替え拡張機能のインストール',
	'index_useragent_extension_install_instructions_1' : 'モバイル・ブラウザー・シミュレーターでユーザー・エージェント ID ストリングの自動切り替えができるようにするため、拡張機能をブラウザーにインストールする必要があります。',
	'index_useragent_extension_install_instructions_2' : 'シミュレーターで現行バージョンの拡張機能がインストールされていないことが検出されました。以下のリンクを使用して、現行のブラウザーに最新の拡張機能をインストールしてください。',
	'index_useragent_extension_install_btn' : 'ブラウザー拡張機能のインストール',
	'index_useragent_extension_install_instructions_chrome1' : '注: 拡張機能のインストールを試行した後で「拡張機能、アプリケーション、およびユーザー・スクリプトは Chrome ウェブストアからのみ追加できます」というメッセージを受け取る場合、拡張機能を手動でインストールする必要があります。以下のステップに従ってください。',
	'index_useragent_extension_install_instructions_chrome2' : 'Chrome の「設定」を開きます',
	'index_useragent_extension_install_instructions_chrome3' : 'Chrome の「拡張機能」ページに移動します',
	'index_useragent_extension_install_instructions_chrome4' : 'ダウンロードした拡張機能ファイルをダウンロード・ツールバーから「拡張機能」ページにドラッグ・アンド・ドロップします。',
	'index_need_http' : "非相対パスを使用する場合は、パスの前に「http://」を付加する必要があります。",
	'index_splash_title' : "ロード中...",
	'index_splash_status' : "まもなくシミュレーターの準備ができます。",	
	'MobileDeviceTree_by_platform' : 'プラットフォーム別',
	'MobileDeviceTree_by_resolution' : '解像度別',
	'MobileDeviceTree_platforms' : 'プラットフォーム',
	'MobileDeviceTree_resolutions' : '解像度',
	'MobileBrowserSimulator_rotate' : '回転',
	'MobileBrowserSimulator_remove_device': 'デバイスの削除',
	'MobileBrowserSimulator_xdomain_warning' : '現在表示されている Web ページは、このテスト・クライアントと異なるサーバーにあります。',
	'MobileBrowserSimulator_skin' : 'スキン',
	'QRCodeTooltip' : 'この QR コードをスキャンしてシミュレートされた Web ページをモバイル・デバイスにロードします。',
	'QRCodeIPTooltip' : 'モバイル・デバイスから、シミュレートされた Web ページへのアクセスに使用する IP またはホスト名を選択もしくは入力する必要があります。',
	'QRCodeIPHostName' : 'IP/ホスト名',
	'PPICalculator_desc' : 'シミュレーターで実行するページをさまざまなモバイル・デバイスの物理的サイズで表示するために、シミュレーターを現在のモニターに合わせて調整する必要があります。',
	'PPICalculator_step_1' : '標準的なサイズのクレジット・カードを画面上部に重ね、カードの上部を黒い実線に合わせてください。',
	'PPICalculator_step_2' : 'グレーの点線をドラッグするか、矢印キーを使用して、カードの下部に合わせてください。',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "Web ブラウザーの現在のバージョンは完全にはサポートされていません。",
	'Downgrade' : "次にダウングレードする必要があります",
	'Upgrade' : "次にアップグレードする必要があります",
	'OrLater' : "もしくはそれ以降",
	'Firefox_version_warning' : "デバイス毎のユーザー・エージェントの切り替えは、Firefox バージョン 17-22 ではサポートされていません。",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "デバイス API のシミュレート",
	'index_cordova_enable_desc' : 'Apache Cordova API シミュレーションを使用可能にします。',	
	'index_cordova_support' : 'Apache Cordova シミュレーションは Android、iPhone、iPad、Windows Phone、Windows 8 および BlackBerry 10 の環境でサポートされており、次のブラウザーでのみ使用可能です:'

//end v1.x content
});

