//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : '在非测试客户机服务器上查看 Web 页面可能导致显著降低测试客户机功能。',

	'index_title' : '移动浏览器模拟器',
	'index_desc' : '移动浏览器模拟器帮助您在各种移动浏览器大小和形状中显示移动 Web 页面。',
	'index_webpage' : 'Web 页面：',
	'index_go' : '转至/刷新',
	'index_go_simple_preview' : '打开简单预览',
	'index_scale' : '缩放所有设备：',
	'index_scale_pp' : '100%',
	'index_scale_fit' : '适合窗口',
	'index_scale_physical' : '物理设备大小',
	'index_add_device' : '添加设备',
	'index_calibrate' : '校准物理大小',
	'index_calibrate_dialog_title' : '物理大小校准',
	'index_scaling_warning' : '移动浏览器模拟器不支持在此浏览器中缩放内容。此移动浏览器模拟器支持在最新版本的 Mozilla Firefox 或 Internet Explorer 9 以及更高版本中缩放内容。',
	'index_xdomain_warning' : '当前显示的 Web 页面位于不同于此测试客户机的服务器上。',
	'index_enable_useragent_switching' : '启用用户代理交换',
	'index_useragent_switching_desc' : '用户代理程序标识交换使模拟器可在浏览器中更改用户代理程序标识，以便当在模拟器中装入页面时，能够使用正确的用户代理程序标识字符串来请求页面。',
	'index_useragent_switching_support' : '以下浏览器上支持用户代理交换：',
	'index_useragent_extension_install_title' : '安装用户代理交换程序扩展',
	'index_useragent_extension_install_instructions_1' : '要使移动浏览器模拟器自动交换用户代理标识字符串，必须在浏览器中安装一个扩展。',
	'index_useragent_extension_install_instructions_2' : '模拟器检测到未安装扩展的当前版本。请使用以下链接来为浏览器安装最新扩展。',
	'index_useragent_extension_install_btn' : '安装浏览器扩展',
	'index_useragent_extension_install_instructions_chrome1' : '注意：如果在尝试安装该扩展后，您得到以下消息“仅可从 Chrome Web 商店添加扩展、应用和用户脚本”，那么您必须手动安装该扩展。要执行的步骤如下所示：',
	'index_useragent_extension_install_instructions_chrome2' : '打开 Chrome 设置',
	'index_useragent_extension_install_instructions_chrome3' : '转至 Chrome 扩展页面',
	'index_useragent_extension_install_instructions_chrome4' : '将下载的扩展文件从下载工具栏拖放到扩展页面。',
	'index_need_http' : "使用非相对路径时，路径前面必须加上“http://”。",
	'index_splash_title' : "正在装入...",
	'index_splash_status' : "模拟器将马上准备就绪。",	
	'MobileDeviceTree_by_platform' : '按平台',
	'MobileDeviceTree_by_resolution' : '按分辨率',
	'MobileDeviceTree_platforms' : '平台',
	'MobileDeviceTree_resolutions' : '分辨率',
	'MobileBrowserSimulator_rotate' : '旋转',
	'MobileBrowserSimulator_remove_device': '除去设备',
	'MobileBrowserSimulator_xdomain_warning' : '当前显示的 Web 页面位于不同于此测试客户机的服务器上。',
	'MobileBrowserSimulator_skin' : '外表',
	'QRCodeTooltip' : '扫描此 QRCode 以在您的移动设备上装入模拟的 Web 页面。',
	'QRCodeIPTooltip' : '从您的移动设备访问模拟的 Web 页面时，必须选择/输入要使用的 IP 地址或主机名。',
	'QRCodeIPHostName' : 'IP/主机名',
	'PPICalculator_desc' : '要查看以各种移动设备的物理大小在模拟器中运行的页面，需要根据当前的监视器校准此模拟器：',
	'PPICalculator_step_1' : '将一张标准大小的信用卡放在屏幕上，以使卡片的顶部与黑色实线对齐。',
	'PPICalculator_step_2' : '拖动灰色的虚线，或使用方向键以与卡片的底部对齐。',
	'Mozilla_Firefox' : 'Mozilla Firefox ',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "不完全支持您当前的 Web 浏览器版本。",
	'Downgrade' : "请降低版本至",
	'Upgrade' : "请升级版本至",
	'OrLater' : "或更高版本",
	'Firefox_version_warning' : "Firefox 版本 17-22 不支持对每个设备切换用户代理。",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "模拟设备 API",
	'index_cordova_enable_desc' : '启用 Apache Cordova API 模拟。',	
	'index_cordova_support' : 'Android、iPhone、iPad、Windows Phone、Windows 8 和 BlackBerry 10 环境均支持 Apache Cordova 模拟，该模拟仅在以下浏览器中可用：'

//end v1.x content
});

