//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'Zobrazení webových stránek, které nebudou na serveru testovacího klienta, způsobí významné snížení funkčnosti testovacího klienta.',

	'index_title' : 'Mobile Browser Simulator',
	'index_desc' : 'Aplikace Mobile Browser Simulator zobrazuje webové stránky mobilních zařízení v různých velikostech a tvarech mobilního prohlížeče.',
	'index_webpage' : 'Webová stránka:',
	'index_go' : 'Přejít / Obnovit',
	'index_go_simple_preview' : 'Otevřít jednoduchý náhled',
	'index_scale' : 'Stupnice všech zařízení:',
	'index_scale_pp' : '100 %',
	'index_scale_fit' : 'Přizpůsobit oknu',
	'index_scale_physical' : 'Fyzická velikost zařízení',
	'index_add_device' : 'Přidat zařízení',
	'index_calibrate' : 'Kalibrovat fyzickou velikost',
	'index_calibrate_dialog_title' : 'Kalibrace fyzické velikosti',
	'index_scaling_warning' : 'Aplikace Mobile Browser Simulator nepodporuje změnu měřítka obsahu v tomto prohlížeči. Aplikace Mobile Browser Simulator podporuje změnu měřítka obsahu v nejnovější verzi prohlížeče Mozilla Firefox nebo v prohlížeči Internet Explorer 9 a vyšším.',
	'index_xdomain_warning' : 'Momentálně zobrazená webová stránka je na odlišném serveru než tento testovací klient.',
	'index_enable_useragent_switching' : 'Povolit přepnutí agenta uživatele',
	'index_useragent_switching_desc' : 'Přepnutí ID agenta uživatele umožní simulátoru změnit ID agenta uživatele v prohlížeči, takže když se stránka načte do simulátoru, bude vyžadováno, aby použila správný řetězec ID agenta uživatele.',
	'index_useragent_switching_support' : 'Přepnutí agenta uživatele je podporováno následujícími prohlížeči:',
	'index_useragent_extension_install_title' : 'Instalovat rozšíření přepínače agenta uživatele',
	'index_useragent_extension_install_instructions_1' : 'Aby mohla aplikace Mobile Browser Simulator automaticky přepínat řetězec ID agenta uživatele, musí být rozšíření nainstalováno na počítači.',
	'index_useragent_extension_install_instructions_2' : 'Simulátor zjistí, zda není aktuální verze rozšíření instalována. Použitím odkazu níže instalujte nejnovější rozšíření aktuálního prohlížeče.',
	'index_useragent_extension_install_btn' : 'Instalovat rozšíření prohlížeče',
	'index_useragent_extension_install_instructions_chrome1' : 'Pozn.: Pokud po pokusu o instalaci přípony obdržíte následující zprávu \"Přípony, aplikace a skripty uživatele lze přidat pouze z webového úložiště Chrome.\", pak musíte příponu nainstalovat ručně. Postupujte podle těchto kroků:',
	'index_useragent_extension_install_instructions_chrome2' : 'Otevřít nastavení prohlížeče Chrome',
	'index_useragent_extension_install_instructions_chrome3' : 'Přejít na stránku přípon prohlížeče Chrome',
	'index_useragent_extension_install_instructions_chrome4' : 'Přetáhnout stažený soubor přípony z panelu nástrojů pro stahování do stránky přípon.',
	'index_need_http' : "Při použití jiné než relativní cesty musí být cesta předřazena 'http://'.",
	'index_splash_title' : "Probíhá načítání...",
	'index_splash_status' : "Simulátor bude za okamžik připraven.",	
	'MobileDeviceTree_by_platform' : 'Podle platformy',
	'MobileDeviceTree_by_resolution' : 'Podle řešení',
	'MobileDeviceTree_platforms' : 'Platformy',
	'MobileDeviceTree_resolutions' : 'Rozlišení',
	'MobileBrowserSimulator_rotate' : 'Otočit',
	'MobileBrowserSimulator_remove_device': 'Odebrat zařízení',
	'MobileBrowserSimulator_xdomain_warning' : 'Momentálně zobrazená webová stránka je na odlišném serveru než tento testovací klient.',
	'MobileBrowserSimulator_skin' : 'Vzhled',
	'QRCodeTooltip' : 'Skenujte tento QRCode k načtení simulované webové stránky na vašem vlastním mobilním zařízení.',
	'QRCodeIPTooltip' : 'Musíte zvolit/zadat adresu IP nebo název hostitele, který se použije pro přístup k simulované webové stránce z vašeho vlastního mobilního zařízení.',
	'QRCodeIPHostName' : 'Adresa IP/Název hostitele',
	'PPICalculator_desc' : 'Chcete-li zobrazit stránku spuštěnou v simulátoru ve fyzické velikosti na různých mobilních zařízeních, musíte simulátor kalibrovat vůči aktuálnímu monitoru:',
	'PPICalculator_step_1' : 'Umístěte standardní platební kartu na obrazovku tak, že vrchní část karty bude zároveň s plnou černou čarou.',
	'PPICalculator_step_2' : 'Přetáhněte tečkovanou šedou čáru, nebo ji pomocí kurzorových kláves zarovnejte se spodní hranou karty.',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "Aktuální verze webového prohlížeče není plně podporována.",
	'Downgrade' : "Měli byste snížit úroveň na",
	'Upgrade' : "Měli byste upgradovat na",
	'OrLater' : "nebo novější",
	'Firefox_version_warning' : "Přepínání agenta uživatele na zařízení není podporováno na prohlížeči Firefox verze 17-22.",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "Simulovat rozhraní API zařízení",
	'index_cordova_enable_desc' : 'Povolte simulaci rozhraní API Apache Cordova.',	
	'index_cordova_support' : 'Simulace Apache Cordova je podporována prostředími Android, iPhone, iPad, Windows Phone, Windows 8 a BlackBerry 10 a je k dispozici pouze na následujících prohlížečích:'

//end v1.x content
});

