//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'La visualización de páginas web en el servidor cliente de prueba provocará una reducción significativa en la función cliente de prueba.',

	'index_title' : 'Simulador de navegador móvil',
	'index_desc' : 'El simulador de navegador móvil muestra páginas web móviles en una variedad de tamaños y formas de navegador móvil.',
	'index_webpage' : 'Página web:',
	'index_go' : 'Ir / Renovar',
	'index_go_simple_preview' : 'Abrir vista previa simple',
	'index_scale' : 'Escala de todos los dispositivos:',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'Ajustar a ventana',
	'index_scale_physical' : 'Tamaño de dispositivo físico',
	'index_add_device' : 'Añadir dispositivo',
	'index_calibrate' : 'Calibrar tamaño físico',
	'index_calibrate_dialog_title' : 'Calibración de tamaño físico',
	'index_scaling_warning' : 'El simulador de navegador móvil no permite escalar el contenido en este navegador. El simulador de navegador móvil permite escalar el contenido en la última versión de Mozilla Firefox o Internet Explorer 9 y posteriores.',
	'index_xdomain_warning' : 'La página web que se visualiza en estos momentos se encuentra en un servidor diferente de este cliente de prueba.',
	'index_enable_useragent_switching' : 'Habilitar la conmutación de agente de usuario',
	'index_useragent_switching_desc' : 'La conmutación de ID de agente de usuario permite que el simulador cambie el ID de agente de usuario en el navegador, para que cuando una página esté cargada en el simulador, la página se solicite con la serie de ID de agente de usuario correcta.',
	'index_useragent_switching_support' : 'La conmutación de agente de usuario está soportada en los navegadores siguientes:',
	'index_useragent_extension_install_title' : 'Instalar extensión del conmutación de agente de usuario',
	'index_useragent_extension_install_instructions_1' : 'Para que el simulador del navegador móvil conmute automáticamente la serie de ID de agente de usuario, debe instalar una extensión en el navegador.',
	'index_useragent_extension_install_instructions_2' : 'El simulador detecta si una versión actual de la extensión no está instalada. Utilice el siguiente enlace para instalar la última extensión del navegador.',
	'index_useragent_extension_install_btn' : 'Instalar extensión de navegador',
	'index_useragent_extension_install_instructions_chrome1' : 'Nota: si después de intentar instalar la extensión, obtiene el siguiente mensaje \"Las extensiones, aplicaciones y scripts de usuario sólo pueden añadirse desde la tienda web Chrome.\", deberá instalar manualmente la extensión. Estos son los pasos que debe seguir:',
	'index_useragent_extension_install_instructions_chrome2' : 'Abra la configuración de Chrome',
	'index_useragent_extension_install_instructions_chrome3' : 'Vaya a la página de ampliaciones de Chrome',
	'index_useragent_extension_install_instructions_chrome4' : 'Arrastre y suelte el archivo de ampliación descargado de la barra de herramientas de descarga a la página de extensiones.',
	'index_need_http' : "Cuando se utiliza una vía de acceso no relativa, debe agregarse 'http://' al principio de la vía de acceso.",
	'index_splash_title' : "Cargando...",
	'index_splash_status' : "El simulador estará listo en un momento.",	
	'MobileDeviceTree_by_platform' : 'Por la plataforma',
	'MobileDeviceTree_by_resolution' : 'Por la resolución',
	'MobileDeviceTree_platforms' : 'Plataformas',
	'MobileDeviceTree_resolutions' : 'Resoluciones',
	'MobileBrowserSimulator_rotate' : 'Rotar',
	'MobileBrowserSimulator_remove_device': 'Quitar dispositivo',
	'MobileBrowserSimulator_xdomain_warning' : 'La página web que se visualiza en estos momentos se encuentra en un servidor diferente de este cliente de  prueba.',
	'MobileBrowserSimulator_skin' : 'Textura',
	'QRCodeTooltip' : 'Explore este QRCode para cargar la página web simulada en su propio dispositivo móvil.',
	'QRCodeIPTooltip' : 'Debe elegir/especificar la IP o el nombre de host que se utilizará para acceder a la página web simulada desde su propio dispositivo móvil.',
	'QRCodeIPHostName' : 'IP/Nombre de host',
	'PPICalculator_desc' : 'Para poder ver la página que se ejecuta en el simulador en el tamaño físico de los diversos dispositivos móviles, debe calibrar el simulador para el monitor de visualización actual:',
	'PPICalculator_step_1' : 'Coloque una tarjeta de crédito estándar en la pantalla de modo que la parte superior de la tarjeta se alinee con la línea de puntos negros uniformes.',
	'PPICalculator_step_2' : 'Arrastre la línea gris de puntos o utilice las teclas de flecha para alinearla con la parte inferior de la tarjeta.',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "La versión actual del navegador web si no está totalmente soportada.",
	'Downgrade' : "Debe degradar a",
	'Upgrade' : "Debe actualizar a",
	'OrLater' : "o posterior",
	'Firefox_version_warning' : "La conmutación de agente de usuario por dispositivo no está soportada en las versiones 17-22 de Firefox.",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "Simular API de dispositivo",
	'index_cordova_enable_desc' : 'Habilitar la simulación de API de Apache Cordova.',	
	'index_cordova_support' : 'La simulación de Apache Cordova está soportada por los entornos Android, iPhone, iPad, Windows Phone, Windows 8 y BlackBerry 10 y sólo está disponible en los siguientes navegadores:'

//end v1.x content
});

