define({
		'sim_common_start' : 'Reproduzir',
		'sim_common_stop' : 'Parar',
		'sim_common_error_button' : 'Gerar Erro',
		'sim_common_error_pending_button' : 'Erro Pendente',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'Avançar',
		'sim_accelerometer_startStop_button' : 'Iniciar / Parar',

		'sim_battery_plugedIn_label' : 'Conectado:',
		'sim_battery_batteryLevel_label' : 'Nível de Bateria:',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : 'Escolha uma imagem a ser usada para a câmera:',
		'sim_camera_currently_selected_camera' : 'Imagem selecionada atualmente para a câmera:',
		'sim_camera_choose_image_album_library' : 'Escolha uma imagem para usar para álbum/biblioteca:',
		'sim_camera_currently_selected_album_library' : 'Imagem selecionada atualmente para álbum/biblioteca:',
		'sim_camera_cannotLoadApplet' : "A simulação da API da câmera está desativada (applet não carregado; verifique suas configurações Java)",

		'sim_camera_xs' : 'PP',
		'sim_camera_s' : 'D',
		'sim_camera_m' : 'S',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Escolher Arquivo(s) de Áudio',
		'sim_capture_audio1' : 'Áudio 1',
		'sim_capture_audio2' : 'Áudio 2',
		'sim_capture_audio3' : 'Áudio 3',
		'sim_capture_playAudio' : 'Reproduzir',
		'sim_capture_choose_video' : 'Escolher Arquivo(s) de Vídeo',
		'sim_capture_video1' : 'Vídeo 1',
		'sim_capture_video2' : 'Vídeo 2',
		'sim_capture_video3' : 'Vídeo 3',
		'sim_capture_playVideo' : 'Reproduzir',
		'sim_capture_browserSupport' : 'A UI de simulação de captura está disponível com o Google Chrome e o Mozilla Firefox.',
		'sim_capture_cannotLoadApplet' : "A simulação da API de captura está desativada (applet não carregado; verifique suas configurações Java)",
		'sim_compass_error_random' : 'Gerar erro aleatório',
		'sim_compass_generate' : 'Gerar',

		'sim_compass_heading_label' : 'Título:',
		'sim_compass_next_button' : 'Avançar',
		'sim_compass_startStop_button' : 'Iniciar / Parar',
		'sim_compass_error_button' : 'Gerar Erro',

		'sim_contacts_refresh_label' : 'Atualizar',
		'sim_contacts_nowebsql' : 'A simulação de API de contatos do Cordova está desativada porque a WebSQL não é suportada neste navegador.',

		'sim_device_select_label' : 'Selecionar Dispositivo:',
		'sim_device_prev_button' : 'Anterior',
		'sim_device_next_button' : 'Avançar',
		'sim_device_no_version_info' : 'Nenhuma informação de versão',

		'sim_events_pause_button' : 'Pausar',
		'sim_events_resume_button' : 'Retomar',
		'sim_events_back_button' : 'Voltar',
		'sim_events_menu_button' : 'a de Menus',
		'sim_events_search_button' : 'Procurar',
		'sim_events_online_button' : 'Online',
		'sim_events_offline_button' : 'Offline',
		'sim_events_startCall_button' : 'Iniciar Chamada',
		'sim_events_endCall_button' : 'Terminar Chamada',
		'sim_events_volumeUp_button' : 'Aumentar Volume',
		'sim_events_volumeDown_button' : 'Diminuir Volume',

		'sim_file_refresh_button' : "Atualizar",
		'sim_file_cannotLoadApplet' : "A simulação da API do arquivo está desativada (applet não carregado; verifique suas configurações Java)",
		'sim_geoloc_longitude_label' : 'Longitude',
		'sim_geoloc_latitude_label' : 'Latitude',
		'sim_geoloc_accuracy_label' : 'Precisão',
		'sim_geoloc_altitude_label' : 'Altitude',
		'sim_geoloc_altitudeAccuracy_label' : 'Precisão da Altitude',
		'sim_geoloc_heading_label' : 'Título',
		'sim_geoloc_velocity_label' : 'Velocidade (m/s)',
		'sim_geoloc_next_button' : "Etapa",
		'sim_geoloc_startStop_button' : "Reproduzir / Parar",
		'sim_geoloc_usingFFgeolocation' : "Usando o serviço de localização geográfica fornecido com o Firefox.",
		'sim_geoloc_apply_tooltip' : "Pressione Aplicar para que as mudanças entrem em vigor",
		'sim_geoloc_step_tooltip' : "Mova uma vez de acordo com o título e a velocidade por 1 segundo.",
		'sim_geoloc_startStop_tooltip' : "Inicie a movimentação de acordo com o título e a velocidade.",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : 'Reprodução',
		'sim_media_length_label' : 'Comprimento',
		'sim_media_audioRecording_label' : 'Gravação de Áudio',
		'sim_media_audioRecording_status' : 'Inativo',
		'sim_media_audioRecording_idle' : 'Inativo',
		'sim_media_audioRecording_recording' : 'Registro',

		'sim_network_none' : 'Nenhum',
		'sim_network_ethernet' : 'Rede Ethernet',
		'sim_network_wifi' : 'Rede Wifi',
		'sim_network_2g' : 'Rede 2G',
		'sim_network_3g' : 'Rede 3G',
		'sim_network_4g' : 'Rede 4G',
		'sim_network_cell' : 'Conexão Genérica de Célula',
		'sim_network_unknown' : 'Rede Desconhecida',
		'sim_scenario_warning' : 'Aviso',
		'sim_scenario_unsaved_text' : '<h3>Você possui mudanças não salvas no cenário atual.</h3><h3>Se você escolher continuar, essas mudanças serão perdidas.</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Latitude, Longitude (graus decimais, por exemplo, -118,15, 34,03)',
		'sim_scenario_usingFFgeolocation' : "O widget de cenário não é suportado no Firefox.",
		'sim_scenario_usingIEgeolocation' : "O widget de cenário não é suportado no Internet Explorer.",
		'sim_scenario_new' : 'Novo',
		'sim_scenario_delete' : 'Delete',
		'sim_scenario_delete_path' : 'Excluir Caminho',
		'sim_scenario_save' : 'Salvar',
		'sim_scenario_pause' : 'Pausar',
		'sim_scenario_play' : 'Reproduzir',
		'sim_scenario_restart' : 'Reiniciar',
		'sim_scenario_continue' : 'Continuar',
		'sim_scenario_edit' : 'Editar',
		'sim_scenario_go' : 'Ir',
		'sim_scenario_cancel' : 'Cancelar',
		'sim_scenario_export' : 'Exportação',
		'sim_scenario_apply' : 'Aplicar',
		'sim_scenario_editor_name' : 'Nome:',
		'sim_scenario_editor_name_textbox_placeholder' : 'Nome do Cenário',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Nome do Cenário</p>',
		'sim_scenario_editor_speed_label' : 'Velocidade (m/s)',
		'sim_scenario_editor_time_label' : 'Horário (s)',
		'sim_scenario_editor_no_gps_zone_title' : 'Nenhuma Zona de GPS',
		'sim_scenario_editor_access_point_title' : 'Ponto de Acesso',
		'sim_scenario_editor_route_point_title' : 'Ponto de Rota',
		'sim_scenario_editor_path_tooltip' : '<p>Criar um caminho simulado de um dispositivo móvel:</p>'+
												'<ul><li>Clique no mapa para incluir vértices (pontos) no caminho</li><li>Clique duas vezes quando concluir</li></ul>' +
												'<p>Depois que o caminho for criado, clique em um vértice para movê-lo ou editar suas propriedades.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>Criar uma zona de WiFi:</p>'+
												'<ul><li>Arraste o mouse para criar a área de cobertura WiFi.</li></ul>' +
												'<p>Depois que a zona de WiFi for criada, clique na zona para movê-la ou editar suas propriedades.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>Criar uma zona sem cobertura de GPS:</p>'+
												'<ul><li>Clique no mapa para incluir vértices (pontos) na zona</li><li>Clique duas vezes quando concluir</li></ul>' +
												'<p>Depois que a zona Sem GPS for criada, clique na zona para movê-la ou editar suas propriedades.</p>'
});

