define({
	root : ({
		'sim_common_start' : 'Play',
		'sim_common_stop' : 'Stop',
		'sim_common_error_button' : 'Generate Error',
		'sim_common_error_pending_button' : 'Error Pending',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'Next',
		'sim_accelerometer_startStop_button' : 'Start / Stop',

		'sim_battery_plugedIn_label' : 'Plugged In:',
		'sim_battery_batteryLevel_label' : 'Battery Level:',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : 'Choose an image to use for camera:',
		'sim_camera_currently_selected_camera' : 'Currently selected image for camera:',
		'sim_camera_choose_image_album_library' : 'Choose an image to use for album/library:',
		'sim_camera_currently_selected_album_library' : 'Currently selected image for album/library:',
		'sim_camera_cannotLoadApplet' : "Camera API simulation is disabled (applet not loaded, please check your Java settings)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Choose Audio File(s)',
		'sim_capture_audio1' : 'Audio 1',
		'sim_capture_audio2' : 'Audio 2',
		'sim_capture_audio3' : 'Audio 3',
		'sim_capture_playAudio' : 'Play',
		'sim_capture_choose_video' : 'Choose Video File(s)',
		'sim_capture_video1' : 'Video 1',
		'sim_capture_video2' : 'Video 2',
		'sim_capture_video3' : 'Video 3',
		'sim_capture_playVideo' : 'Play',
		'sim_capture_browserSupport' : 'The capture simulation UI is available with Google Chrome and Mozilla Firefox.',
		'sim_capture_cannotLoadApplet' : "Capture API simulation is disabled (applet not loaded, please check your Java settings)",
		'sim_compass_error_random' : 'Generate random error',
		'sim_compass_generate' : 'Generate',

		'sim_compass_heading_label' : 'Heading:',
		'sim_compass_next_button' : 'Next',
		'sim_compass_startStop_button' : 'Start / Stop',
		'sim_compass_error_button' : 'Generate Error',

		'sim_contacts_refresh_label' : 'Refresh',
		'sim_contacts_nowebsql' : 'The Cordova contacts API simulation is disabled because WebSQL is not supported in this browser.',
		'sim_contacts_tooltip' : 'Use the Cordova API to add and retrieve contacts.',
		
		'sim_device_select_label' : 'Select Device:',
		'sim_device_prev_button' : 'Previous',
		'sim_device_next_button' : 'Next',
		'sim_device_no_version_info' : 'No version info',

		'sim_events_pause_button' : 'Pause',
		'sim_events_resume_button' : 'Resume',
		'sim_events_back_button' : 'Back',
		'sim_events_menu_button' : 'Menu',
		'sim_events_search_button' : 'Search',
		'sim_events_online_button' : 'Online',
		'sim_events_offline_button' : 'Offline',
		'sim_events_startCall_button' : 'Start Call',
		'sim_events_endCall_button' : 'End Call',
		'sim_events_volumeUp_button' : 'Volume Up',
		'sim_events_volumeDown_button' : 'Volume Down',

		'sim_file_refresh_button' : "Refresh",
		'sim_file_cannotLoadApplet' : "File API simulation is disabled (applet not loaded, please check your Java settings)",
		'sim_file_tooltip' : "Use the Cordova API to read and write to this filesystem.",
		
		
		'sim_geoloc_longitude_label' : 'Longitude',
		'sim_geoloc_latitude_label' : 'Latitude',
		'sim_geoloc_accuracy_label' : 'Accuracy',
		'sim_geoloc_altitude_label' : 'Altitude',
		'sim_geoloc_altitudeAccuracy_label' : 'Altitude Accuracy',
		'sim_geoloc_heading_label' : 'Heading',
		'sim_geoloc_velocity_label' : 'Speed(m/s)',
		'sim_geoloc_next_button' : "Step",
		'sim_geoloc_startStop_button' : "Play / Stop",
		'sim_geoloc_usingFFgeolocation' : "Using the geolocation service provided with Firefox.",
		'sim_geoloc_apply_tooltip' : "Press apply for changes to take affect",
		'sim_geoloc_step_tooltip' : "Move once according to heading and speed per 1 second.",
		'sim_geoloc_startStop_tooltip' : "Start moving according to heading and speed.",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : 'PlayBack',
		'sim_media_length_label' : 'Length',
		'sim_media_audioRecording_label' : 'Audio Recording',
		'sim_media_audioRecording_status' : 'Idle',
		'sim_media_audioRecording_idle' : 'Idle',
		'sim_media_audioRecording_recording' : 'Recording',

		'sim_network_none' : 'None',
		'sim_network_ethernet' : 'Ethernet Network',
		'sim_network_wifi' : 'Wifi Network',
		'sim_network_2g' : '2G Network',
		'sim_network_3g' : '3G Network',
		'sim_network_4g' : '4G Network',
		'sim_network_cell' : 'Cell Generic Connection',
		'sim_network_unknown' : 'Unknown Network',
		'sim_scenario_warning' : 'Warning',
		'sim_scenario_unsaved_text' : '<h3>You have unsaved changes in the current scenario.</h3><h3>If you choose to continue those changes will be lost.</h3>',
		
		'sim_scenario_editor_go_input_placeholder' : 'Latitude, Longitude (decimal degrees, for example -118.15, 34.03)',
		'sim_scenario_usingFFgeolocation' : "The scenario widget is not supported in Firefox.",
		'sim_scenario_usingIEgeolocation' : "The scenario widget is not supported in Internet Explorer.",
		'sim_scenario_new' : 'New',
		'sim_scenario_delete' : 'Delete',
		'sim_scenario_delete_path' : 'Delete path',
		'sim_scenario_save' : 'Save',
		'sim_scenario_pause' : 'Pause',
		'sim_scenario_play' : 'Play',
		'sim_scenario_restart' : 'Restart',
		'sim_scenario_continue' : 'Continue',
		'sim_scenario_edit' : 'Edit',
		'sim_scenario_go' : 'Go',
		'sim_scenario_cancel' : 'Cancel',
		'sim_scenario_export' : 'Export',
		'sim_scenario_apply' : 'Apply',
		'sim_scenario_editor_name' : 'Name:',
		'sim_scenario_editor_name_textbox_placeholder' : 'Scenario name',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Scenario name</p>',
		
		'sim_scenario_editor_speed_label' : 'Speed (m/s)',
		'sim_scenario_editor_time_label' : 'Time (s)',
		
		'sim_scenario_editor_no_gps_zone_title' : 'No GPS Zone',
		'sim_scenario_editor_access_point_title' : 'Access Point',
		'sim_scenario_editor_access_point_editor_title': 'Access Point',
		'sim_scenario_editor_route_point_title' : 'Route Point',
		'sim_scenario_editor_path_tooltip' : '<p>Create a simulated path of a mobile device:</p>'+
												'<ul><li>Click the map to add vertices (points) to the path</li><li>Double-click when you finish</li></ul>' +
												'<p>After the path is created, click a vertex to move it or edit its properties.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>Create a WiFi zone:</p>'+
												'<ul><li>Drag the mouse to create the WiFi coverage area.</li></ul>' +
												'<p>After the WiFi zone is created, click the zone to move it or edit its properties.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>Create a zone with no GPS coverage:</p>'+
												'<ul><li>Click the map to add vertices (points) to the zone</li><li>Double-click when you finish</li></ul>' +
												'<p>After the No GPS zone is created, click the zone to move it or edit its properties.</p>'
	})
	,
	"pt-br": true,
	"cs" : true,
	"fr": true,
	"de": true,
	"hu": true,
	"it": true,
	"ja": true,
	"ko": true,
	"pl": true,
	"ru": true,
	"zh-cn": true,
	"es": true,
	"zh-tw": true,
	"ar": true
});
