//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : '不在測試用戶端伺服器上檢視網頁，將導致測試用戶端功能顯著減少。',

	'index_title' : '行動式瀏覽器模擬器',
	'index_desc' : '「行動式瀏覽器模擬器」會以各種行動式瀏覽器大小及形狀顯示行動式網頁。',
	'index_webpage' : '網頁：',
	'index_go' : '執行/重新整理',
	'index_go_simple_preview' : '開啟簡式預覽',
	'index_scale' : '調整所有裝置的大小：',
	'index_scale_pp' : '100%',
	'index_scale_fit' : '符合視窗大小',
	'index_scale_physical' : '實體裝置大小',
	'index_add_device' : '新增裝置',
	'index_calibrate' : '校準實體大小',
	'index_calibrate_dialog_title' : '實體大小校準',
	'index_scaling_warning' : '「行動式瀏覽器模擬器」不支援在此瀏覽器中調整內容大小。「行動式瀏覽器模擬器」支援在最新版本的 Mozilla Firefox 或 Internet Explorer 9 以及更高版本中調整內容大小。',
	'index_xdomain_warning' : '目前顯示的網頁與此測試用戶端位於不同的伺服器上。',
	'index_enable_useragent_switching' : '啟用使用者代理程式切換',
	'index_useragent_switching_desc' : '使用者代理程式 ID 切換可讓模擬器變更瀏覽器中的使用者代理程式 ID，以便在模擬器中載入頁面時，使用正確的使用者代理程式 ID 字串要求頁面。',
	'index_useragent_switching_support' : '下列瀏覽器上支援使用者代理程式切換：',
	'index_useragent_extension_install_title' : '安裝使用者代理程式切換器延伸',
	'index_useragent_extension_install_instructions_1' : '為了讓「行動式瀏覽器模擬器」自動切換使用者代理程式 ID 字串，必須在瀏覽器中安裝延伸。',
	'index_useragent_extension_install_instructions_2' : '「模擬器」偵測到未安裝現行版本的延伸。請使用下面的鏈結，為當前瀏覽器安裝最新的延伸。',
	'index_useragent_extension_install_btn' : '安裝瀏覽器延伸',
	'index_useragent_extension_install_instructions_chrome1' : '附註：如果嘗試安裝延伸之後，您取得下列訊息「只能從 Chrome Web Store 新增延伸、應用程式及使用者 Script。」，則必須手動安裝延伸。以下是要遵循的步驟：',
	'index_useragent_extension_install_instructions_chrome2' : '開啟 Chrome 設定',
	'index_useragent_extension_install_instructions_chrome3' : '跳至 Chrome 延伸頁面',
	'index_useragent_extension_install_instructions_chrome4' : '將所下載的延伸檔從下載工具列拖放至延伸頁面。',
	'index_need_http' : "當使用非相對路徑時，必須將 'http://' 附加到路徑的前面。",
	'index_splash_title' : "正在載入...",
	'index_splash_status' : "模擬器馬上備妥。",	
	'MobileDeviceTree_by_platform' : '依平台',
	'MobileDeviceTree_by_resolution' : '依解析',
	'MobileDeviceTree_platforms' : '平台',
	'MobileDeviceTree_resolutions' : '解析',
	'MobileBrowserSimulator_rotate' : '旋轉',
	'MobileBrowserSimulator_remove_device': '移除裝置',
	'MobileBrowserSimulator_xdomain_warning' : '目前顯示的網頁與此測試用戶端位於不同的伺服器上。',
	'MobileBrowserSimulator_skin' : '外觀',
	'QRCodeTooltip' : '掃描此 QRCode 以將模擬網頁負載到您的行動式裝置。',
	'QRCodeIPTooltip' : '必須選擇/輸入 IP 或主機名稱，用來從您的行動式裝置存取模擬網頁。',
	'QRCodeIPHostName' : 'IP/主機名',
	'PPICalculator_desc' : '為了使用各種行動式裝置的實體大小來檢視模擬器中正在執行的頁面，您需要按照現行顯示器校準模擬器：',
	'PPICalculator_step_1' : '將標準大小信用卡放置到畫面上，以便卡的頂端與黑色實線對齊。',
	'PPICalculator_step_2' : '拖曳灰色點虛線，或者使用方向鍵，來與卡的底端對齊。',
	'Mozilla_Firefox' : 'Mozilla Firefox ',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "Web 瀏覽器的現行版本不能完全支援。",
	'Downgrade' : "您需要降級到",
	'Upgrade' : "您需要升級到",
	'OrLater' : "或更高版本",
	'Firefox_version_warning' : "Firefox 17-22 版不支援在每個裝置上切換使用者代理程式。",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "模擬裝置 API",
	'index_cordova_enable_desc' : '啟用 Apache Cordova API 模擬。',	
	'index_cordova_support' : 'Apache Cordova 模擬受 Android、iPhone、iPad、Windows Phone、Windows 8 及 BlackBerry 10 環境支援，且只能用於下列瀏覽器上：'

//end v1.x content
});

