define({
		'sim_common_start' : 'Lecture',
		'sim_common_stop' : 'Arrêt',
		'sim_common_error_button' : 'Générer une erreur',
		'sim_common_error_pending_button' : 'Erreur en attente',

		'sim_accelerometer_accelX_label' : 'X :',
		'sim_accelerometer_accelY_label' : 'Y :',
		'sim_accelerometer_accelZ_label' : 'Z :',
		'sim_accelerometer_nextAccel_button' : 'Suivant',
		'sim_accelerometer_startStop_button' : 'Démarrer / Arrêter',

		'sim_battery_plugedIn_label' : 'Branché :',
		'sim_battery_batteryLevel_label' : 'Niveau de la batterie :',

		'sim_battery_hrule_labels' : '0 %,20 %,40 %,60 %,80 %,100 %',

		'sim_camera_choose_image_camera' : 'Sélectionnez une image à utiliser pour la caméra:',
		'sim_camera_currently_selected_camera' : 'Image actuellement sélectionnée pour la caméra :',
		'sim_camera_choose_image_album_library' : 'Choisissez une image à utiliser pour l\'album/la bibliothèque :',
		'sim_camera_currently_selected_album_library' : 'Image actuellement sélectionnée pour l\'album/la bibliothèque :',
		'sim_camera_cannotLoadApplet' : "La simulation de l'API de la caméra est désactivée (applet non chargée, vérifiez vos paramètres Java)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Choisir le(s) fichier(s) audio',
		'sim_capture_audio1' : 'Audio 1',
		'sim_capture_audio2' : 'Audio 2',
		'sim_capture_audio3' : 'Audio 3',
		'sim_capture_playAudio' : 'Lecture',
		'sim_capture_choose_video' : 'Choisir le(s) fichier(s) vidéo',
		'sim_capture_video1' : 'Vidéo 1',
		'sim_capture_video2' : 'Vidéo 2',
		'sim_capture_video3' : 'Vidéo 3',
		'sim_capture_playVideo' : 'Lecture',
		'sim_capture_browserSupport' : 'L\'interface utilisateur de simulation de la capture est disponible avec Google Chrome et Mozilla Firefox.',
		'sim_capture_cannotLoadApplet' : "La simulation de l'API de la caméra est désactivée (applet non chargée, vérifiez vos paramètres Java)",
		'sim_compass_error_random' : 'Générer une erreur aléatoire',
		'sim_compass_generate' : 'Générer',

		'sim_compass_heading_label' : 'En-tête :',
		'sim_compass_next_button' : 'Suivant',
		'sim_compass_startStop_button' : 'Démarrer / Arrêter',
		'sim_compass_error_button' : 'Générer une erreur',

		'sim_contacts_refresh_label' : 'Actualiser',
		'sim_contacts_nowebsql' : 'La simulation de l\'API Cordova contacts est désactivée car WebSQL n\'est pas pris en charge par ce navigateur.',

		'sim_device_select_label' : 'Sélectionnez un appareil :',
		'sim_device_prev_button' : 'Précédent',
		'sim_device_next_button' : 'Suivant',
		'sim_device_no_version_info' : 'Pas d\'informations sur la version',

		'sim_events_pause_button' : 'Interrompre',
		'sim_events_resume_button' : 'Reprendre',
		'sim_events_back_button' : 'Précédent',
		'sim_events_menu_button' : 'Menu',
		'sim_events_search_button' : 'Recherche',
		'sim_events_online_button' : 'En ligne',
		'sim_events_offline_button' : 'Hors ligne',
		'sim_events_startCall_button' : 'Démarrer l\'appel',
		'sim_events_endCall_button' : 'Terminer l\'appel',
		'sim_events_volumeUp_button' : 'Volume +',
		'sim_events_volumeDown_button' : 'Baisse du volume',

		'sim_file_refresh_button' : "Actualiser",
		'sim_file_cannotLoadApplet' : "La simulation de l'API File est désactivée (applet non chargée, vérifiez vos paramètres Java)",
		'sim_geoloc_longitude_label' : 'Longitude',
		'sim_geoloc_latitude_label' : 'Latitude',
		'sim_geoloc_accuracy_label' : 'Tolérance',
		'sim_geoloc_altitude_label' : 'Altitude',
		'sim_geoloc_altitudeAccuracy_label' : 'Précision de l\'altitude',
		'sim_geoloc_heading_label' : 'En-tête',
		'sim_geoloc_velocity_label' : 'Vitesse (m/s)',
		'sim_geoloc_next_button' : "Etape",
		'sim_geoloc_startStop_button' : "Lecture / Arrêt",
		'sim_geoloc_usingFFgeolocation' : "Utilisation du service de géolocalisation fourni avec Firefox.",
		'sim_geoloc_apply_tooltip' : "Appuyez sur Appliquer pour que les modifications prennent effet",
		'sim_geoloc_step_tooltip' : "Déplacez-vous une fois selon la direction et la vitesse pendant 1 seconde.",
		'sim_geoloc_startStop_tooltip' : "Commencez à vous déplacer selon la direction et la vitesse.",

		'sim_media_url_label' : 'URL :',
		'sim_media_playBack_label' : 'Lecture',
		'sim_media_length_label' : 'Longueur',
		'sim_media_audioRecording_label' : 'Enregistrement audio',
		'sim_media_audioRecording_status' : 'Inactif',
		'sim_media_audioRecording_idle' : 'Inactif',
		'sim_media_audioRecording_recording' : 'Enregistrement',

		'sim_network_none' : 'Aucun',
		'sim_network_ethernet' : 'Réseau Ethernet',
		'sim_network_wifi' : 'Réseau Wifi',
		'sim_network_2g' : 'Réseau 2G',
		'sim_network_3g' : 'Réseau 3G',
		'sim_network_4g' : 'Réseau 4G',
		'sim_network_cell' : 'Connexion de cellule générique',
		'sim_network_unknown' : 'Réseau inconnu',
		'sim_scenario_warning' : 'Avertissement',
		'sim_scenario_unsaved_text' : '<h3>Vous avez des modifications non enregistrées dans le scénario actuel.</h3><h3>Si vous choisissez de continuer, ces modifications seront perdues.</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Latitude, longitude (en degrés décimaux, par exemple -118.15, 34.03)',
		'sim_scenario_usingFFgeolocation' : "Le widget de scénario n'est pas supporté dans Firefox.",
		'sim_scenario_usingIEgeolocation' : "Le widget de scénario n'est pas supporté dans Internet Explorer.",
		'sim_scenario_new' : 'Nouveau',
		'sim_scenario_delete' : 'Supprimer',
		'sim_scenario_delete_path' : 'Supprimer le chemin',
		'sim_scenario_save' : 'Enregistrer',
		'sim_scenario_pause' : 'Pause',
		'sim_scenario_play' : 'Lecture',
		'sim_scenario_restart' : 'Redémarrer',
		'sim_scenario_continue' : 'Continuer',
		'sim_scenario_edit' : 'Editer',
		'sim_scenario_go' : 'Lancer',
		'sim_scenario_cancel' : 'Annuler',
		'sim_scenario_export' : 'Exporter',
		'sim_scenario_apply' : 'Appliquer',
		'sim_scenario_editor_name' : 'Nom :',
		'sim_scenario_editor_name_textbox_placeholder' : 'Nom du scénario',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Nom du scénario</p>',
		'sim_scenario_editor_speed_label' : 'Vitesse (m/s)',
		'sim_scenario_editor_time_label' : 'Temps (s)',
		'sim_scenario_editor_no_gps_zone_title' : 'Aucune zone GPS',
		'sim_scenario_editor_access_point_title' : 'Point d\'accès',
		'sim_scenario_editor_route_point_title' : 'Point de passage',
		'sim_scenario_editor_path_tooltip' : '<p>Créez un trajet simulé d\'un appareil mobile :</p>'+
												'<ul><li>Cliquez sur le plan pour ajouter des points au trajet</li><li>Cliquez deux fois lorsque vous avez fini</li></ul>' +
												'<p>Une fois le trajet créé, cliquez sur un point pour le déplacer ou modifier ses propriétés.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>Créez une zone WiFi :</p>'+
												'<ul><li>Faites glisser la souris pour créer la zone de couverture WiFi.</li></ul>' +
												'<p>Une fois la zone WiFi créée, cliquez dessus pour la déplacer ou modifier ses propriétés.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>Créez une zone sans couverture GPS :</p>'+
												'<ul><li>Cliquez sur le plan pour ajouter des points à la zone</li><li>Cliquez deux fois lorsque vous avez fini</li></ul>' +
												'<p>Une fois la zone sans couverture GPS créée, cliquez dessus pour la déplacer ou modifier ses propriétés.</p>'
});

