define({
		'sim_common_start' : '再生',
		'sim_common_stop' : '停止',
		'sim_common_error_button' : 'エラーの生成',
		'sim_common_error_pending_button' : 'エラーの保留',

		'sim_accelerometer_accelX_label' : 'X: ',
		'sim_accelerometer_accelY_label' : 'Y: ',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : '次へ',
		'sim_accelerometer_startStop_button' : '開始/停止',

		'sim_battery_plugedIn_label' : '接続場所:',
		'sim_battery_batteryLevel_label' : 'バッテリー・レベル:',

		'sim_battery_hrule_labels' : '0%,20%,40%,60%,80%,100%',

		'sim_camera_choose_image_camera' : 'カメラに使用するイメージの選択:',
		'sim_camera_currently_selected_camera' : '現在選択されているカメラのイメージ:',
		'sim_camera_choose_image_album_library' : 'アルバム/ライブラリーに使用するイメージの選択:',
		'sim_camera_currently_selected_album_library' : '現在選択されているアルバム/ライブラリーのイメージの選択:',
		'sim_camera_cannotLoadApplet' : "カメラ API シミュレーションは使用不可です (アプレットはロードされません。Java 設定を確認してください)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'オーディオ・ファイルの選択',
		'sim_capture_audio1' : 'オーディオ 1',
		'sim_capture_audio2' : 'オーディオ 2',
		'sim_capture_audio3' : 'オーディオ 3',
		'sim_capture_playAudio' : '再生',
		'sim_capture_choose_video' : 'ビデオ・ファイルの選択',
		'sim_capture_video1' : 'ビデオ 1',
		'sim_capture_video2' : 'ビデオ 2',
		'sim_capture_video3' : 'ビデオ 3',
		'sim_capture_playVideo' : '再生',
		'sim_capture_browserSupport' : 'キャプチャー・シミュレーション UI は、Google Chrome および Mozilla Firefox で使用可能です。',
		'sim_capture_cannotLoadApplet' : "キャプチャー API シミュレーションは使用不可です (アプレットはロードされません。Java 設定を確認してください)",
		'sim_compass_error_random' : 'ランダムなエラーの生成',
		'sim_compass_generate' : '生成',

		'sim_compass_heading_label' : '見出し:',
		'sim_compass_next_button' : '次へ',
		'sim_compass_startStop_button' : '開始/停止',
		'sim_compass_error_button' : 'エラーの生成',

		'sim_contacts_refresh_label' : '更新',
		'sim_contacts_nowebsql' : 'このブラウザーでは WebSQL がサポートされていないため、Cordova Contacts API シミュレーションは使用不可です。',

		'sim_device_select_label' : 'デバイスの選択:',
		'sim_device_prev_button' : '前へ',
		'sim_device_next_button' : '次へ',
		'sim_device_no_version_info' : 'バージョン情報はありません',

		'sim_events_pause_button' : '一時停止',
		'sim_events_resume_button' : '再開',
		'sim_events_back_button' : '戻る',
		'sim_events_menu_button' : 'メニュー',
		'sim_events_search_button' : '検索',
		'sim_events_online_button' : 'オンライン',
		'sim_events_offline_button' : 'オフライン',
		'sim_events_startCall_button' : '呼び出しの開始',
		'sim_events_endCall_button' : '呼び出しの終了',
		'sim_events_volumeUp_button' : 'ボリュームを上げる',
		'sim_events_volumeDown_button' : 'ボリュームを下げる',

		'sim_file_refresh_button' : "更新",
		'sim_file_cannotLoadApplet' : "ファイル API シミュレーションは使用不可です (アプレットはロードされません。Java 設定を確認してください)",
		'sim_geoloc_longitude_label' : '経度',
		'sim_geoloc_latitude_label' : '緯度',
		'sim_geoloc_accuracy_label' : '精度',
		'sim_geoloc_altitude_label' : '高度',
		'sim_geoloc_altitudeAccuracy_label' : '高度の精度',
		'sim_geoloc_heading_label' : '見出し',
		'sim_geoloc_velocity_label' : '速度 (メートル/秒)',
		'sim_geoloc_next_button' : "ステップ",
		'sim_geoloc_startStop_button' : "再生 / 停止",
		'sim_geoloc_usingFFgeolocation' : "Firefox で提供される地理位置情報サービスを使用しています。",
		'sim_geoloc_apply_tooltip' : "「適用」を押して、変更を有効にします",
		'sim_geoloc_step_tooltip' : "方角と 1 秒当たりの速度に応じて1 回移動します。",
		'sim_geoloc_startStop_tooltip' : "方角と速度に応じて移動を開始します。",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : '再生',
		'sim_media_length_label' : '長さ',
		'sim_media_audioRecording_label' : '録音',
		'sim_media_audioRecording_status' : 'アイドル',
		'sim_media_audioRecording_idle' : 'アイドル',
		'sim_media_audioRecording_recording' : '記録中',

		'sim_network_none' : 'なし',
		'sim_network_ethernet' : 'イーサネット・ネットワーク',
		'sim_network_wifi' : 'WiFi ネットワーク',
		'sim_network_2g' : '2G ネットワーク',
		'sim_network_3g' : '3G ネットワーク',
		'sim_network_4g' : '4G ネットワーク',
		'sim_network_cell' : 'ジェネリック・コネクションのコール',
		'sim_network_unknown' : '不明なネットワーク',
		'sim_scenario_warning' : '警告',
		'sim_scenario_unsaved_text' : '<h3>現在のシナリオに、保存していない変更があります。</h3><h3>続行すると、保存していない変更はすべて失われます。</h3>',
		'sim_scenario_editor_go_input_placeholder' : '緯度、経度 (10 進表記、例: -118.15、34.03)',
		'sim_scenario_usingFFgeolocation' : "シナリオ・ウィジェットは Firefox でサポートされていません。",
		'sim_scenario_usingIEgeolocation' : "シナリオ・ウィジェットは Internet Explorer でサポートされていません。",
		'sim_scenario_new' : '新規',
		'sim_scenario_delete' : '削除',
		'sim_scenario_delete_path' : 'パスの削除',
		'sim_scenario_save' : '保存',
		'sim_scenario_pause' : '一時停止',
		'sim_scenario_play' : '再生',
		'sim_scenario_restart' : '再始動',
		'sim_scenario_continue' : '続行',
		'sim_scenario_edit' : '編集',
		'sim_scenario_go' : '実行',
		'sim_scenario_cancel' : 'キャンセル ',
		'sim_scenario_export' : 'エクスポート',
		'sim_scenario_apply' : '適用',
		'sim_scenario_editor_name' : '名前:',
		'sim_scenario_editor_name_textbox_placeholder' : 'シナリオ名',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">シナリオ名</p>',
		'sim_scenario_editor_speed_label' : '速度 (メートル/秒)',
		'sim_scenario_editor_time_label' : '時間 (秒)',
		'sim_scenario_editor_no_gps_zone_title' : 'GPS ゾーンがありません',
		'sim_scenario_editor_access_point_title' : 'アクセス・ポイント',
		'sim_scenario_editor_route_point_title' : '経路ポイント',
		'sim_scenario_editor_path_tooltip' : '<p>モバイル・デバイスのシミュレートされたパスを作成:</p>'+
												'<ul><li>マップをクリックして、パスの頂点 (ポイント) を追加します</li><li>終了後、ダブルクリックします</li></ul>' +
												'<p>パスが作成された後、クリックして頂点を移動させるか、頂点のプロパティーを編集します。</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>WiFi ゾーンの作成:</p>'+
												'<ul><li>マウスをドラッグして、WiFi カバレッジ領域を作成します。</li></ul>' +
												'<p>WiFi ゾーンが作成された後、ゾーンをクリックして移動するか、ゾーンのプロパティーを編集します。</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>GPS カバレッジのないゾーンの作成:</p>'+
												'<ul><li>マップをクリックして、ゾーンへの頂点 (ポイント) を追加します</li><li>終了後、ダブルクリックします</li></ul>' +
												'<p>GPS のないゾーンが作成された後、ゾーンをクリックして移動するか、ゾーンのプロパティーを編集します。</p>'
});

