//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'Wyświetlanie stron WWW nie na serwerze klienta testowego spowoduje znaczne ograniczenie działania klienta testowego.',

	'index_title' : 'Mobile Browser Simulator',
	'index_desc' : 'Produkt Mobile Browser Simulator pozwala na wyświetlanie stron WWW dla urządzeń przenośnych w przeglądarkach urządzeń przenośnych o różnych wielkościach i kształtach.',
	'index_webpage' : 'Strona WWW:',
	'index_go' : 'Przejdź / Odśwież',
	'index_go_simple_preview' : 'Otwórz prosty podgląd',
	'index_scale' : 'Skaluj wszystkie urządzenia:',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'Dopasuj do okna',
	'index_scale_physical' : 'Wielkość urządzenia fizycznego',
	'index_add_device' : 'Dodaj urządzenie',
	'index_calibrate' : 'Kalibruj wielkość fizyczną',
	'index_calibrate_dialog_title' : 'Kalibrowanie wielkości fizycznej',
	'index_scaling_warning' : 'Produkt Mobile Browser Simulator nie obsługuje skalowania treści w tej przeglądarce. Produkt Mobile Browser Simulator obsługuje skalowanie treści w najnowszej wersji przeglądarki Mozilla Firefox lub Internet Explorer 9.',
	'index_xdomain_warning' : 'Aktualnie wyświetlona strona WWW znajduje się na innym serwerze niż ten klient testowy.',
	'index_enable_useragent_switching' : 'Włącz przełączanie agenta użytkownika',
	'index_useragent_switching_desc' : 'Przełączanie identyfikatora agenta użytkownika umożliwia symulatorowi zmianę tego identyfikatora w przeglądarce. Oznacza to, że gdy strona zostanie załadowana w symulatorze, strona jest żądana przy użyciu poprawnego łańcucha identyfikatora agenta użytkownika.',
	'index_useragent_switching_support' : 'Przełączanie agenta użytkownika jest obsługiwane w następujących przeglądarkach:',
	'index_useragent_extension_install_title' : 'Instaluj rozszerzenie przełącznika agenta użytkownika',
	'index_useragent_extension_install_instructions_1' : 'Aby produkt Mobile Browser Simulator automatycznie przełączył łańcuch identyfikatora agenta użytkownika, rozszerzenie musi być zainstalowane w przeglądarce.',
	'index_useragent_extension_install_instructions_2' : 'Symulator wykrył, że nie jest zainstalowana bieżąca wersja rozszerzenia. Skorzystaj z poniższego odsyłacza, aby zainstalować najnowsze rozszerzenie dla używanej przeglądarki.',
	'index_useragent_extension_install_btn' : 'Instaluj rozszerzenie przeglądarki',
	'index_useragent_extension_install_instructions_chrome1' : 'Informacja: Jeśli po próbie zainstalowania rozszerzenia zostanie wyświetlony następujący komunikat: Extensions, apps, and user scripts can only be added from the Chrome Web Store (Rozszerzenia, aplikacje i skrypty użytkownika można dodawać tylko ze sklepu Chrome Web Store), należy ręcznie zainstalować rozszerzenie. W tym celu wykonaj następujące kroki:',
	'index_useragent_extension_install_instructions_chrome2' : 'Otwórz ustawienia przeglądarki Chrome.',
	'index_useragent_extension_install_instructions_chrome3' : 'Przejdź na stronę rozszerzeń przeglądarki Chrome.',
	'index_useragent_extension_install_instructions_chrome4' : 'Przeciągnij pobrany plik rozszerzenia z paska narzędzi pobierania i upuść go na stronę rozszerzeń.',
	'index_need_http' : "Jeśli używana jest ścieżka bezwzględna, należy wstawić na początek łańcuch http://.",
	'index_splash_title' : "Ładowanie...",
	'index_splash_status' : "Symulator za chwilę będzie gotowy do użycia.",	
	'MobileDeviceTree_by_platform' : 'Według platformy',
	'MobileDeviceTree_by_resolution' : 'Według rozdzielczości',
	'MobileDeviceTree_platforms' : 'Platformy',
	'MobileDeviceTree_resolutions' : 'Rozdzielczości',
	'MobileBrowserSimulator_rotate' : 'Obróć',
	'MobileBrowserSimulator_remove_device': 'Usuń urządzenie',
	'MobileBrowserSimulator_xdomain_warning' : 'Aktualnie wyświetlona strona WWW znajduje się na innym serwerze niż ten klient testowy.',
	'MobileBrowserSimulator_skin' : 'Skóra',
	'QRCodeTooltip' : 'Przeprowadź skanowanie tego kodu QR, aby załadować symulowaną stronę WWW do urządzenia przenośnego.',
	'QRCodeIPTooltip' : 'Należy wybrać/wprowadzić adres IP lub nazwę hosta na potrzeby uzyskiwania dostępu do symulowanej strony WWW z poziomu urządzenia przenośnego.',
	'QRCodeIPHostName' : 'Adres IP / nazwa hosta',
	'PPICalculator_desc' : 'Aby wyświetlić stronę działającą w symulatorze o wielkości fizycznej różnych urządzeń przenośnych, należy skalibrować symulator dla bieżącego monitora:',
	'PPICalculator_step_1' : 'Umieść na ekranie kartę kredytową o standardowej wielkości tak, aby górna część karty przylegała do czarnej linii ciągłej.',
	'PPICalculator_step_2' : 'Przeciągnij szarą linię kropkowaną lub użyj klawiszy strzałek, aby wyrównać ją z dolną częścią karty.',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "Bieżąca wersja przeglądarki WWW nie jest w pełni obsługiwana.",
	'Downgrade' : "Należy przejść na następującą starszą wersję:",
	'Upgrade' : "Należy przeprowadzić aktualizację do wersji",
	'OrLater' : "lub nowszej",
	'Firefox_version_warning' : "Przełączanie agenta użytkownika na poszczególnych urządzeniach nie jest obsługiwane w przypadku następujących wersji przeglądarki Firefox: 17-22.",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "Interfejs API symulacji urządzenia",
	'index_cordova_enable_desc' : 'Włącz symulację interfejsu API Apache Cordova.',	
	'index_cordova_support' : 'Symulacja Apache Cordova jest obsługiwana przez środowiska Android, iPhone, iPad, Windows Phone, Windows 8 i BlackBerry 10 oraz jest dostępna tylko w następujących przeglądarkach:'

//end v1.x content
});

