//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'A tesztügyféltől eltérő kiszolgálón található weboldalak megjelenítése jelentősen szűkíti a tesztügyfél funkcióit. ',

	'index_title' : 'Mobilböngésző-szimulátor',
	'index_desc' : 'A Mobilböngésző-szimulátor mobil weboldalakat jelenít meg többféle mobilböngésző méretének és alakjának megfelelően.',
	'index_webpage' : 'Weboldal:',
	'index_go' : 'Ugrás / Frissítés',
	'index_go_simple_preview' : 'Egyszerű előkép megnyitása',
	'index_scale' : 'Összes eszköz méretezése:',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'Igazítás az ablakhoz',
	'index_scale_physical' : 'Fizikai eszköz mérete',
	'index_add_device' : 'Eszköz hozzáadása',
	'index_calibrate' : 'Fizikai méret kalibrálása',
	'index_calibrate_dialog_title' : 'Fizikai méret kalibrálása',
	'index_scaling_warning' : 'A Mobilböngésző-szimulátor nem támogatja a tartalom átméretezését ebben a böngészőben. A mobilböngésző-szimulátor a tartalom átméretezését csak a legfrissebb Mozilla Firefox böngészőben, illetve az Internet Explorer 9-es és újabb kiadásaiban támogatja. ',
	'index_xdomain_warning' : 'A jelenleg megjelenő weboldal a tesztügyféltől eltérő kiszolgálón található. ',
	'index_enable_useragent_switching' : 'Böngészőazonosítás átkapcsolásának engedélyezése',
	'index_useragent_switching_desc' : 'A böngészőazonosítás átkapcsolása lehetővé teszi a szimulátornak a böngésző azonosítójának módosítását, így az oldalak betöltésekor a tartalom kérése a megfelelő böngészőazonosítási karaktersorozat megadásával történik. ',
	'index_useragent_switching_support' : 'A böngészőazonosítás átkapcsolása az alábbi böngészőkben támogatott:',
	'index_useragent_extension_install_title' : 'Felhasználóügynök átkapcsoló bővítmény telepítése',
	'index_useragent_extension_install_instructions_1' : 'Ahhoz, hogy a mobilböngésző-szimulátor automatikusan át tudja állítani a böngészőazonosító karaktersorozatot, telepíteni kell egy bővítményt a böngészőre. ',
	'index_useragent_extension_install_instructions_2' : 'A szimulátor megállapította, hogy a bővítmény aktuális változata nincs telepítve. Az alábbi hivatkozás segítségével telepítse a böngészőjéhez rendelkezésre álló legfrissebb bővítményt. ',
	'index_useragent_extension_install_btn' : 'Böngészőbővítmény telepítése',
	'index_useragent_extension_install_instructions_chrome1' : 'Megjegyzés: Ha a bővítmény telepítésére tett kísérlet után a következő üzenetet kapja: \"Bővítmények, alkalmazások és felhasználói parancsfájlok csak a Chrome webtárból adhatók hozzá.\", akkor saját kezűleg kell bővítményt telepítenie. Ehhez tegye a következőket:',
	'index_useragent_extension_install_instructions_chrome2' : 'Nyissa meg a Chrome beállításokat',
	'index_useragent_extension_install_instructions_chrome3' : 'Menjen a Bővítmények oldalra',
	'index_useragent_extension_install_instructions_chrome4' : 'Fogja meg és húzza a letöltött bővítményfájlt a letöltési eszköztárból a Bővítmények oldalra.',
	'index_need_http' : "Nem-relatív útvonal használatakor az elérési út elé ki kell tenni a 'http://' meghatározást.",
	'index_splash_title' : "Betöltés...",
	'index_splash_status' : "A szimulátor pár pillanat múlva üzemkész. ",	
	'MobileDeviceTree_by_platform' : 'Platform szerint',
	'MobileDeviceTree_by_resolution' : 'Felbontás szerint',
	'MobileDeviceTree_platforms' : 'Platformok',
	'MobileDeviceTree_resolutions' : 'Felbontások',
	'MobileBrowserSimulator_rotate' : 'Forgatás',
	'MobileBrowserSimulator_remove_device': 'Eszköz eltávolítása',
	'MobileBrowserSimulator_xdomain_warning' : 'A jelenleg megjelenő weboldal a tesztügyféltől eltérő kiszolgálón található. ',
	'MobileBrowserSimulator_skin' : 'Felszín',
	'QRCodeTooltip' : 'Olvassa le a QR-kódot a szimulált weboldal betöltéséhez a mobileszközén. ',
	'QRCodeIPTooltip' : 'Ki kell választani vagy meg kell adni az IP címet vagy hosztnevet, amellyel a mobileszközéről eléri a szimulált weboldalt. ',
	'QRCodeIPHostName' : 'IP/hosztnév',
	'PPICalculator_desc' : 'Ahhoz, hogy a szimulátor a különböző mobileszközök fizikai méretének megfelelően tudja megjeleníteni a weboldalakat, kalibrálni kell az aktuális monitort: ',
	'PPICalculator_step_1' : 'Helyezzen egy szabványos bankkártyát a képernyőre úgy, hogy a kártya teteje a képernyőn látható folytonos fekete vonalra essen. ',
	'PPICalculator_step_2' : 'Húzza (vagy a nyilak segítségével mozgassa) a szaggatott szürke vonalat a kártya aljához. ',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "A böngésző jelenlegi változatának támogatása nem teljes körű. ",
	'Downgrade' : "Vissza kell térnie a következő változatra: ",
	'Upgrade' : "Frissítenie kell a következő változatra: ",
	'OrLater' : "vagy újabb",
	'Firefox_version_warning' : "A böngészőazonosítás átkapcsolása eszközönként nem támogatott a Firefox 17-22 változataiban. ",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "Eszköz API szimulálása",
	'index_cordova_enable_desc' : 'Az Apache Cordova API szimulációjának engedélyezése.',	
	'index_cordova_support' : 'Az Apache Cordova szimulációt az Android, iPhone, iPad, Windows Phone, Windows 8 és BlackBerry 10 környezetek támogatják és csak a következő böngészőkön áll rendelkezésre:'

//end v1.x content
});

