//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'مشاهدة صفحات الانترنت على وحدة خدمة الوحدة التابعة للاختبار سيتسبب في نقص كبير في وظيفة وحدة الاختبار التابعة.',

	'index_title' : 'برنامج محاكاة استعراض التليفون المحمول',
	'index_desc' : 'برنامج محاكاة استعراض التليفون المحمول يعرض صفحات الانترنت للتليفون المحمول في أحجام وأشكال متنوعة لبرنامج استعراض التليفون المحمول.',
	'index_webpage' : 'صفحة انترنت:',
	'index_go' : 'بدء / تجديد',
	'index_go_simple_preview' : 'فتح المعاينة البسيطة',
	'index_scale' : 'قياس كل الأجهزة:',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'ملائمة للنافذة',
	'index_scale_physical' : 'الحجم المادي للجهاز',
	'index_add_device' : 'اضافة جهاز',
	'index_calibrate' : 'معايرة الحجم المادي',
	'index_calibrate_dialog_title' : 'معايرة الحجم المادي',
	'index_scaling_warning' : 'برنامج محاكاة استعراض التليفون المحمول لا يدعم قياس المحتويات في برنامج الاستعراض هذا. برنامج محاكاة استعراض التليفون المحمول يدعم قياس المحتويات في أحدث النسخ من Mozilla Firefox أو Internet Explorer 9 أو أكبر.',
	'index_xdomain_warning' : 'صفحة الانترنت المعروضة حاليا هى على وحدة خدمة مختلفة عن هذه الوحدة التابعة الخاصة بالاختبار.',
	'index_enable_useragent_switching' : 'اتاحة تحويل وكيل المستخدم',
	'index_useragent_switching_desc' : 'تحويل كود تعريف وكيل المستخدم يتيح لبرنامج المحاكاة تغيير كود تعريف وكيل المستخدم في برنامج الاستعراض، حتى اذا تم تحميل صفحة في برنامج المحاكاة يتم طلب الصفحة باستخدام مجموعة حروف كود تعريف وكيل المستخدم الصحيحة.',
	'index_useragent_switching_support' : 'يتم دعم تحويل وكيل المستخدم في برامج الاستعراض التالية:',
	'index_useragent_extension_install_title' : 'تركيب لاحقة وحدة تحويل وكيل المستخدم',
	'index_useragent_extension_install_instructions_1' : 'كي يقوم برنامج محاكاة استعراض التليفون المحمول بتحويل مجموعة حروف كود تعريف وكيل المستخدم آليا، يجب تركيب لاحقة في برنامج الاستعراض.',
	'index_useragent_extension_install_instructions_2' : 'يقوم برنامج المحاكاة باكتشاف أن النسخة الحالية للاحقة لم يتم تركيبها. قم باستخدام الوصلة بأسفل لتركيب أحدث لاحقة لبرنامج الاستعراض الحالي.',
	'index_useragent_extension_install_btn' : 'تركيب لاحقة برنامج الاستعراض',
	'index_useragent_extension_install_instructions_chrome1' : 'ملحوظة: اذا بعد محاولة تركيب اللاحقة ظهرت لك الرسالة التالية \"يمكن اضافة اللاحقات، والتطبيقات، والبرامج النصية فقط من وحدة تخزين شبكة انترنت Chrome.\"، فيجب عليك القيام بتركيب اللاحقة يدويا. اتبع الخطوات التالية:',
	'index_useragent_extension_install_instructions_chrome2' : 'افتح محددات Chrome',
	'index_useragent_extension_install_instructions_chrome3' : 'اذهب الى صفحة لاحقات Chrome',
	'index_useragent_extension_install_instructions_chrome4' : 'سحب ووضع ملف اللاحقة الذي تم تحميله من خط أدوات التحميل الى صفحة اللاحقات.',
	'index_need_http' : "عند استخدام مسار غير نسبى، يجب اضافة 'http://' فى أول المسار.",
	'index_splash_title' : "تحميل...",
	'index_splash_status' : "سوف يكون المحاكى جاهزا خلال دقيقة فقط.",	
	'MobileDeviceTree_by_platform' : 'ببيئة التشغيل',
	'MobileDeviceTree_by_resolution' : 'بالحل',
	'MobileDeviceTree_platforms' : 'بيئات التشغيل',
	'MobileDeviceTree_resolutions' : 'الحلول',
	'MobileBrowserSimulator_rotate' : 'تدوير',
	'MobileBrowserSimulator_remove_device': 'ازالة جهاز',
	'MobileBrowserSimulator_xdomain_warning' : 'صفحة الانترنت المعروضة حاليا هى على وحدة خدمة مختلفة عن هذه الوحدة التابعة الخاصة بالاختبار.',
	'MobileBrowserSimulator_skin' : 'الشكل العام',
	'QRCodeTooltip' : 'قم بمسح كود الرد السريع لتحميل صفحة الانترنت التى تم محاكاتها على جهاز التليفون المحمول الخاص بك.',
	'QRCodeIPTooltip' : 'يجب عليك اخختيار/ادخال بروتوكول الانترنت أو اسم النظام الرئيسي الذى سوف يتم استخدامه للتوصل الى صفحة الانترنت التى تم محاكتها من جهاز التليفون المحمول الخاص بك.',
	'QRCodeIPHostName' : 'بروتوكول الانترنت/اسم النظام الرئيسى',
	'PPICalculator_desc' : 'لمشاهدة الصفحة التي يتم تشغيلها في برنامج المحاكاة على الحجم المادي لأجهزة تليفونات المحمول المتنوعة، يجب معايرة برنامج المحاكاة الى الشاشة الحالية:',
	'PPICalculator_step_1' : 'ضع بطاقة الائتمان بالحجم القياسي أعلى الشاشة حتى تكون أعلى البطاقة متوازية مع الخط الأسود المصمت.',
	'PPICalculator_step_2' : 'قم بسحب الخط الرمادي المنقط أو استخدم مفاتيح الأسهم لتوازي أسفل البطاقة.',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "لا يتم دعم النسخة الحالية من برنامج استعراض الانترنت الخاص بك بشكل كامل.",
	'Downgrade' : "يجب عليك خفض المستوى الى",
	'Upgrade' : "يجب عليك تطوير النسخة الى",
	'OrLater' : "أو ما بعد ذلك",
	'Firefox_version_warning' : "لا يتم دعم تحويل وكيل المستخدم لكل جهاز على Firefox النسخة 17-22.",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "واجهة تعامل برمجة تطبيق جهاز المحاكاة",
	'index_cordova_enable_desc' : 'يمكن اتاحة محاكاة واجهة تعامل برمجة تطبيق Apache Cordova.',	
	'index_cordova_support' : 'يتم دعم محاكاة Apache Cordova ببيئات تشغيل Android و iPhone و iPad و Windows Phone و Windows 8 و BlackBerry 10 وتجده متاح على برامج الاستعراض التالية فقط:'

//end v1.x content
});

