define({
		'sim_common_start' : 'Play',
		'sim_common_stop' : 'Stoppen',
		'sim_common_error_button' : 'Generierung - Fehler',
		'sim_common_error_pending_button' : 'Fehler - anstehend',

		'sim_accelerometer_accelX_label' : 'X:',
		'sim_accelerometer_accelY_label' : 'Y:',
		'sim_accelerometer_accelZ_label' : 'Z:',
		'sim_accelerometer_nextAccel_button' : 'Nächste/s/r',
		'sim_accelerometer_startStop_button' : 'Starten / Stoppen',

		'sim_battery_plugedIn_label' : 'Plug-in:',
		'sim_battery_batteryLevel_label' : 'Akkustand:',

		'sim_battery_hrule_labels' : '0 %, 20 %, 40 %, 60 %, 80 %, 100 %',

		'sim_camera_choose_image_camera' : 'Ein Bild für die Kamera auswählen:',
		'sim_camera_currently_selected_camera' : 'Momentan ausgewähltes Bild für Kamera:',
		'sim_camera_choose_image_album_library' : 'Ein Bild für das Album/Archiv auswählen:',
		'sim_camera_currently_selected_album_library' : 'Momentan ausgewähltes Bild für Album/Archiv:',
		'sim_camera_cannotLoadApplet' : "Die API-Kamerasimulation ist inaktiviert (Applet nicht geladen; überprüfen Sie Ihre Java-Einstellungen)",

		'sim_camera_xs' : 'XS',
		'sim_camera_s' : 'S',
		'sim_camera_m' : 'M',
		'sim_camera_l' : 'L',
		'sim_camera_xl' : 'XL',

		'sim_capture_choose_audio' : 'Audiodatei(en) auswählen',
		'sim_capture_audio1' : 'Audio 1',
		'sim_capture_audio2' : 'Audio 2',
		'sim_capture_audio3' : 'Audio 3',
		'sim_capture_playAudio' : 'Play',
		'sim_capture_choose_video' : 'Videodatei(en) auswählen',
		'sim_capture_video1' : 'Video 1',
		'sim_capture_video2' : 'Video 2',
		'sim_capture_video3' : 'Video 3',
		'sim_capture_playVideo' : 'Play',
		'sim_capture_browserSupport' : 'Die Benutzerschnittstelle für die Aufzeichnungssimulation ist in Google Chrome und Mozilla Firefox verfügbar.',
		'sim_capture_cannotLoadApplet' : "Die API-Erfassungssimulation ist inaktiviert (Applet nicht geladen; überprüfen Sie Ihre Java-Einstellungen)",
		'sim_compass_error_random' : 'Zufallsfehler generieren',
		'sim_compass_generate' : 'Generieren',

		'sim_compass_heading_label' : 'Kopfzeile:',
		'sim_compass_next_button' : 'Nächste/s/r',
		'sim_compass_startStop_button' : 'Starten / Stoppen',
		'sim_compass_error_button' : 'Generierung - Fehler',

		'sim_contacts_refresh_label' : 'Aktualisieren',
		'sim_contacts_nowebsql' : 'Die Cordova-API-Simulation (\'contacts\') wird inaktiviert, da WebSQL in diesem Browser nicht unterstützt wird.',

		'sim_device_select_label' : 'Gerät auswählen:',
		'sim_device_prev_button' : 'Vorherige/s/r',
		'sim_device_next_button' : 'Nächste/s/r',
		'sim_device_no_version_info' : 'Keine Versionsinformationen',

		'sim_events_pause_button' : 'Pause',
		'sim_events_resume_button' : 'Wieder aufnehmen',
		'sim_events_back_button' : 'Zurück',
		'sim_events_menu_button' : 'Menü',
		'sim_events_search_button' : 'Suche',
		'sim_events_online_button' : 'Online',
		'sim_events_offline_button' : 'Offline',
		'sim_events_startCall_button' : 'Aufruf starten',
		'sim_events_endCall_button' : 'Aufruf beenden',
		'sim_events_volumeUp_button' : 'Lauter',
		'sim_events_volumeDown_button' : 'Leiser',

		'sim_file_refresh_button' : "Aktualisieren",
		'sim_file_cannotLoadApplet' : "Die API-Dateisimulation ist inaktiviert (Applet nicht geladen; überprüfen Sie Ihre Java-Einstellungen)",
		'sim_geoloc_longitude_label' : 'Längengrad',
		'sim_geoloc_latitude_label' : 'Breitengrad',
		'sim_geoloc_accuracy_label' : 'Genauigkeit',
		'sim_geoloc_altitude_label' : 'Höhe',
		'sim_geoloc_altitudeAccuracy_label' : 'Genauigkeit der Höhe',
		'sim_geoloc_heading_label' : 'Kopfzeile',
		'sim_geoloc_velocity_label' : 'Geschwindigkeit (m/s)',
		'sim_geoloc_next_button' : "Abschnitt",
		'sim_geoloc_startStop_button' : "Play / Stoppen",
		'sim_geoloc_usingFFgeolocation' : "Verwendung des mit Firefox bereitgestellten Service für Geolokalisierung.",
		'sim_geoloc_apply_tooltip' : "Drücken Sie auf die Schaltfläche 'Anwenden', damit die Änderungen wirksam werden",
		'sim_geoloc_step_tooltip' : "Entsprechend der Kopfzeile und der Geschwindigkeit pro Sekunde einmal bewegen.",
		'sim_geoloc_startStop_tooltip' : "Entsprechend der Kopfzeile und der Geschwindigkeit bewegen.",

		'sim_media_url_label' : 'URL:',
		'sim_media_playBack_label' : 'PlayBack',
		'sim_media_length_label' : 'Länge',
		'sim_media_audioRecording_label' : 'Tonaufnahme',
		'sim_media_audioRecording_status' : 'Inaktiv',
		'sim_media_audioRecording_idle' : 'Inaktiv',
		'sim_media_audioRecording_recording' : 'Aufnahme',

		'sim_network_none' : 'Kein',
		'sim_network_ethernet' : 'Ethernet-Netz',
		'sim_network_wifi' : 'Wifi-Netz',
		'sim_network_2g' : '2 G Netz',
		'sim_network_3g' : '3 G Netz',
		'sim_network_4g' : '4 G Netz',
		'sim_network_cell' : 'Generische Zellenverbindung',
		'sim_network_unknown' : 'Unbekanntes Netz',
		'sim_scenario_warning' : 'Warnung',
		'sim_scenario_unsaved_text' : '<h3>Im aktuellen Szenario befinden sich nicht gespeicherte Änderungen.</h3><h3>Wenn Sie fortfahren, gehen diese Änderungen verloren.</h3>',
		'sim_scenario_editor_go_input_placeholder' : 'Breitengrad, Längengrad (Dezimalgrade, z. B. -118,15, 34,03)',
		'sim_scenario_usingFFgeolocation' : "Das Szenariowidget wird in Firefox nicht unterstützt.",
		'sim_scenario_usingIEgeolocation' : "Das Szenariowidget wird in Internet Explorer nicht unterstützt.",
		'sim_scenario_new' : 'Neu',
		'sim_scenario_delete' : 'Löschen',
		'sim_scenario_delete_path' : 'Pfad löschen',
		'sim_scenario_save' : 'Speichern',
		'sim_scenario_pause' : 'Pause',
		'sim_scenario_play' : 'Play',
		'sim_scenario_restart' : 'Erneut starten',
		'sim_scenario_continue' : 'Fortfahren',
		'sim_scenario_edit' : 'Bearbeiten',
		'sim_scenario_go' : 'Los',
		'sim_scenario_cancel' : 'Abbrechen',
		'sim_scenario_export' : 'Exportieren',
		'sim_scenario_apply' : 'Anwenden',
		'sim_scenario_editor_name' : 'Name:',
		'sim_scenario_editor_name_textbox_placeholder' : 'Szenarioname',
		'sim_scenario_editor_name_textbox_promptMessage' : '<p class="help">Szenarioname</p>',
		'sim_scenario_editor_speed_label' : 'Geschwindigkeit (m/s)',
		'sim_scenario_editor_time_label' : 'Zeit (Sek.)',
		'sim_scenario_editor_no_gps_zone_title' : 'Keine GPS-Zone',
		'sim_scenario_editor_access_point_title' : 'Zugriffspunkt',
		'sim_scenario_editor_route_point_title' : 'Routenpunkt',
		'sim_scenario_editor_path_tooltip' : '<p>Simulierten Pfad einer mobilen Einheit erstellen:</p>'+
												'<ul><li>Klicken Sie auf die Karte, um Scheitelpunkte (Punkte) zu dem Pfad hinzuzufügen</li><li>Doppelklicken Sie, wenn Sie fertig sind</li></ul>' +
												'<p>Nachdem der Pfad erstellt ist, klicken Sie auf einen Scheitelpunkt, um ihn zu verschieben oder seine Eigenschaften zu bearbeiten.</p>',
		'sim_scenario_editor_wifi_tooltip' : '<p>WiFi-Zone erstellen:</p>'+
												'<ul><li>Ziehen Sie die Maus, um den WiFi-Abdeckungsbereich zu erstellen.</li></ul>' +
												'<p>Nachdem die WiFi-Zone erstellt ist, klicken Sie auf die Zone, um sie zu verschieben oder ihre Eigenschaften zu bearbeiten.</p>',
		'sim_scenario_editor_no_gps_tooltip' : '<p>Zone ohne GPS-Abdeckung erstellen:</p>'+
												'<ul><li>Klicken Sie auf die Karte, um Scheitelpunkte (Punkte) zu der Zone hinzuzufügen</li><li>Doppelklicken Sie, wenn Sie fertig sind</li></ul>' +
												'<p>Nachdem die GPS-freie Zone erstellt ist, klicken Sie auf die Zone, um sie zu verschieben oder ihre Eigenschaften zu bearbeiten.</p>'
});

