//>>built
define({      
//begin v1.x content
	'xdomain_reduced_func' : 'Das Anzeigen von Seiten auf einer anderen Maschine als dem Testclient-Server verursacht eine massive Funktionsbeeinträchtigung des Testclients.',

	'index_title' : 'Mobile Browser Simulator',
	'index_desc' : 'Der Mobile Browser Simulator zeigt mobile Webseiten in einer Vielzahl von Größen und Formen von Browsern an.',
	'index_webpage' : 'Webseite:',
	'index_go' : 'Los / Aktualisieren',
	'index_go_simple_preview' : 'Einfache Voranzeige öffnen',
	'index_scale' : 'Alle Einheiten skalieren:',
	'index_scale_pp' : '100%',
	'index_scale_fit' : 'An Fenstergröße anpassen',
	'index_scale_physical' : 'Größe der physischen Einheit',
	'index_add_device' : 'Einheit hinzufügen',
	'index_calibrate' : 'Physische Größe kalibrieren',
	'index_calibrate_dialog_title' : 'Kalibrierung der physischen Größe',
	'index_scaling_warning' : 'Der Mobile Browser Simulator unterstützt kein Inhalts-Scaling in diesem Browser. Der Mobile Browser Simulator unterstützt Inhalts-Scaling in der aktuellsten Version von Mozilla Firefox oder Internet Explorer 9 und höher.',
	'index_xdomain_warning' : 'Die Seite, die gegenwärtig angezeigt wird, befindet sich auf einem anderen Server als dieser Testclient.',
	'index_enable_useragent_switching' : 'Wechsel des Benutzeragenten aktivieren',
	'index_useragent_switching_desc' : 'Die Aktivierung des Wechsels der Benutzeragenten-ID ermöglicht dem Simulator, die Benutzeragenten-ID im zu ändern, damit eine Seite, die in dem Simulator geladen worden ist, unter Verwendung der korrekten Zeichenfolge der Benutzeragenten-ID angefordert wird.',
	'index_useragent_switching_support' : 'Der Wechsel des Benutzeragenten wird auf den folgenden Browsern unterstützt:',
	'index_useragent_extension_install_title' : 'Erweiterung für Benutzeragentenwechsel installieren',
	'index_useragent_extension_install_instructions_1' : 'Damit der Mobile Browser Simulator automatisch die Zeichenfolge der Benutzeragenten-ID wechselt, muss im Browser eine Erweiterung installiert werden.',
	'index_useragent_extension_install_instructions_2' : 'Der Simulator hat festgestellt, dass keine aktuelle Version der Erweiterung installiert ist. Folgen Sie dem Link unten, um die neueste Erweiterung für den Browser zu installieren.',
	'index_useragent_extension_install_btn' : 'Browsererweiterung installieren',
	'index_useragent_extension_install_instructions_chrome1' : 'Hinweis: Wenn Sie nach dem Versuch einer Installation der Erweiterung folgende Nachricht angezeigt bekommen, müssen die Erweiterung manuell installieren: \"Extensions, apps, and user scripts can only be added from the Chrome Web Store.\". Führen Sie die folgenden Schritte aus:',
	'index_useragent_extension_install_instructions_chrome2' : 'Öffnen Sie die Chrome-Einstellungen.',
	'index_useragent_extension_install_instructions_chrome3' : 'Wechseln Sie zur Chrome-Erweiterungsseite.',
	'index_useragent_extension_install_instructions_chrome4' : 'Ziehen Sie die heruntergeladene Erweiterungsdatei aus der Download-Symbolleiste und legen Sie sie auf der Erweiterungsseite ab.',
	'index_need_http' : "Bei Verwendung eines absoluten (nicht relativen) Pfads muss der Pfadangabe die Zeichenfolge 'http://' vorangestellt werden.",
	'index_splash_title' : "Ladevorgang läuft...",
	'index_splash_status' : "Der Simulator ist in ein paar Augenblicken fertig.",	
	'MobileDeviceTree_by_platform' : 'Nach Plattform',
	'MobileDeviceTree_by_resolution' : 'Nach Auflösung',
	'MobileDeviceTree_platforms' : 'Plattformen',
	'MobileDeviceTree_resolutions' : 'Auflösungen',
	'MobileBrowserSimulator_rotate' : 'Drehen',
	'MobileBrowserSimulator_remove_device': 'Einheit entfernen',
	'MobileBrowserSimulator_xdomain_warning' : 'Die Webseite, die gegenwärtig angezeigt wird, befindet sich auf einem anderen Server als dieser Testclient.',
	'MobileBrowserSimulator_skin' : 'Oberfläche',
	'QRCodeTooltip' : 'Scannen Sie diesen QRCode, um die simulierte Webseite auf Ihre eigene mobile Einheit zu laden.',
	'QRCodeIPTooltip' : 'Sie müssen die IP oder den Hostnamen auswählen/eingeben, die/der für den Zugriff auf die simulierte Webseite über Ihre eigene mobile Einheit verwendet wird.',
	'QRCodeIPHostName' : 'IP/Hostname',
	'PPICalculator_desc' : 'Zum Anzeigen der Seite, die im Simulator in der physischen Größe der diversen mobilen Einheiten ausgeführt wird, muss Simulator auf den aktuellen Monitor kalibrieren werden:',
	'PPICalculator_step_1' : 'Halten Sie eine Kreditkarte mit Standardgröße so an die Anzeige, dass sich der obere Rand der Kreditkarte mit der durchgezogenen schwarzen Linie deckt.',
	'PPICalculator_step_2' : 'Ziehen Sie die gepunktete graue Linie so in Position (oder verwenden Sie hierzu die Pfeiltasten), dass eine Ausrichtung mit dem unteren Rand der Karte gegeben ist.',
	'Mozilla_Firefox' : 'Mozilla Firefox',
	'Google_Chrome' : 'Google Chrome',
	'Safari' : 'Safari',
	'Internet_Explorer' : 'Internet Explorer',
	'IncorrectBrowser' : "Die aktuelle Version Ihres Web-Browsers wird nicht vollständig unterstützt.",
	'Downgrade' : "Downgrade erforderlich auf",
	'Upgrade' : "Upgrade erforderlich auf",
	'OrLater' : "oder höher",
	'Firefox_version_warning' : "Benutzeragentenswitching pro Einheit wird für die Firefox-Versionen 17 - 22 nicht unterstützt.",

	// Apache Cordova support specific labels.
	'index_enable_cordova' : "Einheiten-API simulieren",
	'index_cordova_enable_desc' : 'Aktivieren Sie die Apache Cordova-API-Simulation.',	
	'index_cordova_support' : 'Die Apache Cordova-Simulation wird von den Android-, iPhone-, iPad-, Windows Phone-, Windows 8- und BlackBerry 10-Umgebungen unterstützt und ist nur für die folgenden Browser verfügbar:'

//end v1.x content
});

